(in-package #:tb-tests)

(defun check-bert-batch-tokenizer (model folder real)
  (let ((cases (tb::read-json (merge-pathnames "batch-tokenizer-reference.json" folder)))
        (maximum 0.0))
    (map nil
         (lambda (reference)
           (multiple-value-bind (ids mask types)
               (tb:encode-batch model (gethash "texts" reference)
                                :text-pairs (gethash "text_pairs" reference)
                                :add-special-tokens (tb::json-true-p (gethash "special" reference))
                                :padding (if (equal (gethash "padding" reference) "longest")
                                             :longest :max-length)
                                :max-length (gethash "max_length" reference)
                                :truncation (tb::json-true-p (gethash "truncation" reference)))
             (dolist (entry `((,ids . "input_ids") (,mask . "attention_mask") (,types . "token_type_ids")))
               (check (equalp (car entry) (json-array (gethash (cdr entry) reference)))
                      "native batch tokenization matches Transformers"))
             (tb:with-resource (logits (tb:forward model ids :attention-mask mask :token-type-ids types))
               (setf maximum
                     (max maximum
                          (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference))
                                        (if real 5e-4 3e-5) 3e-4))))
             (when (gethash "labels" reference)
               (multiple-value-bind (loss gradients)
                   (tb:loss-and-gradients model ids :attention-mask mask :token-type-ids types
                                          :labels (json-array (gethash "labels" reference)))
                 (unwind-protect
                      (check (< (abs (- loss (gethash "loss" reference))) 2e-5)
                             "paired text feeds native masked-token training")
                   (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients))))))
         cases)
    (format t "~&BERT text-batch logits max error: ~E~%" maximum))
  (dolist (arguments '((nil) (("Lisp") :text-pairs #())
                       (("Lisp") :text-pairs (7)) (("Lisp") :padding :left)
                       (("Lisp") :padding :max-length) (("Lisp") :truncation t)
                       (("Lisp") :max-length 0) (("Lisp") :truncation :only-first)
                       (("Lisp") :pad-token-id -1)
                       (("Common Lisp") :max-length 2)
                       (("Common") :text-pairs ("Lisp") :truncation t :max-length 2)
                       (("") :add-special-tokens nil)))
    (signals tb:compatibility-error (apply #'tb:encode-batch model arguments)))
  (signals tb:compatibility-error
    (tb:encode-batch model (list (format nil "Lisp~Cignored" #\Null))))
  (signals tb:compatibility-error
    (tb:encode-batch model '("Lisp" "Common Lisp") :pad-token-id nil))
  (multiple-value-bind (ids mask types)
      (tb:encode-batch model '("Lisp" "Lisp") :pad-token-id nil)
    (check (and ids mask types) "equal-length batches do not require a padding token"))
  (let ((before (tb:encode-text model "Common Lisp is fast and fun")))
    (tb:encode-batch model '("Common Lisp is fast and fun") :max-length 4 :truncation t)
    (check (equalp before (tb:encode-text model "Common Lisp is fast and fun"))
           "batch truncation does not mutate the resident tokenizer")))

(defun check-bert-token-types (model folder root device real)
  (let* ((reference (tb::read-json (merge-pathnames "token-type-reference.json" folder)))
         (ids (json-array (gethash "input_ids" reference)))
         (mask (json-array (gethash "attention_mask" reference)))
         (types (json-array (gethash "token_type_ids" reference)))
         (labels (unless real (json-array (gethash "labels" reference)))))
    (tb:with-resource (logits (tb:forward model ids :attention-mask mask :token-type-ids types))
      (format t "~&BERT token-type ~A max error: ~E~%" device
              (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference))
                            (if real 5e-4 3e-5) 3e-4)))
    (unless real
      (dotimes (row 2)
        (flet ((row-array (source)
                 (let ((out (make-array '(1 5))))
                   (dotimes (i 5 out) (setf (aref out 0 i) (aref source row i))))))
          (tb:with-resource (logits (tb:forward model (row-array ids)
                                     :attention-mask (row-array mask) :token-type-ids (row-array types)))
            (close-arrays (tb:tensor-array logits)
                          (json-array (vector (aref (gethash "logits" reference) row))))))))
    (tb:with-resource (default (tb:forward model ids :attention-mask mask))
      (tb:with-resource (zeros (tb:forward model ids :attention-mask mask
                               :token-type-ids (make-array '(2 5) :initial-element 0)))
        (close-arrays (tb:tensor-array default) (tb:tensor-array zeros) 0 0)))
    (dolist (invalid (list #(0 1) (make-array '(1 5) :initial-element 0)
                          (make-array '(2 5) :initial-element -1)
                          (make-array '(2 5) :initial-element 2)
                          (make-array '(2 5) :initial-element 1.0)))
      (signals tb:shape-error (tb:forward model ids :token-type-ids invalid))
      (unless real
        (signals tb:shape-error
          (tb:loss-and-gradients model ids :labels labels :token-type-ids invalid))))
    (unless real
      (multiple-value-bind (loss gradients)
          (tb:loss-and-gradients model ids :labels labels :attention-mask mask :token-type-ids types)
        (let ((expected (make-hash-table :test 'equal)))
          (unwind-protect
               (progn
                 (tb::load-weights (merge-pathnames "token-type-gradients.safetensors" folder)
                                  (tb:model-backend model) expected)
                 (check (< (abs (- loss (gethash "loss" reference))) 2e-5) "BERT segment loss")
                 (check (= (length gradients) (hash-table-count expected)) "BERT segment gradients")
                 (dolist (entry gradients)
                   (close-arrays (tb:tensor-array (cdr entry))
                                 (tb:tensor-array (gethash (car entry) expected)) 4e-6 4e-4)))
            (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)
            (maphash (lambda (name value) (declare (ignore name)) (tb:dispose value)) expected))))
      (tb:with-resource (updated (tb:from-pretrained folder :device device))
        (tb:sgd-step updated ids :labels labels :attention-mask mask
                     :token-type-ids types :learning-rate 0.01)
        (tb:save-pretrained updated
                           (merge-pathnames (format nil ".build/bert-token-type-updated-~(~A~)/" device)
                                            root)))
      (tb:with-resource (trained (tb:from-pretrained folder :device device))
        (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001))
          (let ((checkpoint (merge-pathnames
                              (format nil ".build/bert-token-type-checkpoint-~(~A~)/" device) root)))
            (tb:train-step trained optimizer ids :labels labels :attention-mask mask :token-type-ids types)
            (tb:save-training-checkpoint trained optimizer checkpoint)
            (signals tb:shape-error
              (tb:train-step trained optimizer ids :labels labels :token-type-ids #(0 1)))
            (tb:with-resource (resumed (tb:from-pretrained checkpoint :device device))
              (tb:with-resource (resumed-optimizer (tb:make-adamw :learning-rate 0.001))
                (tb:restore-training-checkpoint resumed resumed-optimizer checkpoint)
                (check (= (tb:train-step trained optimizer ids :labels labels
                                        :attention-mask mask :token-type-ids types)
                          (tb:train-step resumed resumed-optimizer ids :labels labels
                                         :attention-mask mask :token-type-ids types))
                       "BERT segment training resumes after an invalid batch"))))))
      (tb:with-resource (worker (tb:from-pretrained folder :device device :execution :python
                                                  :auto-class "AutoModelForMaskedLM"
                                                  :local-files-only t))
        (tb:with-resource (logits (tb:forward worker ids :attention-mask mask :token-type-ids types))
          (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference))))
        (signals tb:shape-error (tb:forward worker ids :token-type-ids #(0 1)))
        (tb:with-resource (optimizer (tb:make-sgd :learning-rate 0.01))
          (check (< (abs (- (tb:train-step worker optimizer ids :labels labels
                                         :attention-mask mask :token-type-ids types)
                           (gethash "loss" reference))) 2e-5)
                 "Python generic training preserves token types"))
        (tb:with-resource (updated (tb:from-pretrained
                                    (merge-pathnames "token-type-updated/" folder) :device device))
          (tb:with-resource (native-logits (tb:forward updated ids :attention-mask mask :token-type-ids types))
            (tb:with-resource (python-logits (tb:forward worker ids :attention-mask mask :token-type-ids types))
              (close-arrays (tb:tensor-array native-logits) (tb:tensor-array python-logits)))))))))

(defun run-bert-tests ()
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (real (uiop:getenv "TB_BERT_REAL"))
         (folder (merge-pathnames (if real ".build/models/bert-base-uncased/"
                                      ".build/fixtures/bert/") root))
         (reference (tb::read-json (merge-pathnames "reference.json" folder)))
         (ids (json-array (gethash "input_ids" reference)))
         (mask (json-array (gethash "attention_mask" reference)))
         (labels (and (not real) (json-array (gethash "labels" reference))))
         (expected (json-array (gethash "logits" reference)))
         (atol (if real 5e-4 3e-5)))
    (let* ((capabilities (tb:inspect-pretrained folder))
           (operations (getf capabilities :operations)))
      (check (eq (getf capabilities :architecture) :bert)
             "BERT architecture is discoverable")
      (check (every (lambda (operation) (member operation operations))
                    '(:forward :export :tokenization :batch-tokenization :lora :rslora :token-type-ids))
             "BERT masked-LM operations are discoverable")
      (check (eq (not real) (not (null (member :training operations))))
             "BERT training capability follows configured dropout")
      (check (eq (not real) (not (null (member :training-checkpoint operations))))
             "BERT checkpoint capability follows configured dropout")
      (check (not (member :cache operations)) "BERT cache is absent from capabilities")
      (check (not (member :generation operations)) "BERT generation is absent"))
    (tb:with-resource (model (tb:from-pretrained folder :device device))
      (check (typep model 'tb::bert-masked-lm) "BERT masked-LM architecture dispatch")
      (check (= (if real 202 42) (length (tb:named-parameters model)))
             "BERT canonical parameter coverage")
      (check-bert-batch-tokenizer model folder real)
      (check-bert-token-types model folder root device real)
      (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
        (format t "~&BERT masked LM ~A max error: ~E~%" device
                (close-arrays (tb:tensor-array logits) expected atol 3e-4)))
      (let* ((tokenizer (tb::read-json (merge-pathnames "tokenizer-reference.json" folder)))
             (encoded (tb:encode-text model (gethash "text" tokenizer)
                                      :add-special-tokens t)))
        (check (equalp encoded (gethash "ids" tokenizer)) "BERT WordPiece tokenizer IDs")
        (check (equal (tb:decode-tokens model encoded) (gethash "decoded" tokenizer))
               "BERT WordPiece tokenizer decode"))
      (signals tb:compatibility-error (tb:make-cache model))
      (if real
          (signals tb:compatibility-error
            (tb:loss-and-gradients model ids :labels ids :attention-mask mask))
          (progn
            (multiple-value-bind (loss gradients)
                (tb:loss-and-gradients model ids :labels labels :attention-mask mask)
              (let ((expected-gradients (make-hash-table :test 'equal)))
                (unwind-protect
                     (progn
                       (tb::load-weights (merge-pathnames "gradients.safetensors" folder)
                                         (tb:model-backend model) expected-gradients)
                       (check (< (abs (- loss (gethash "loss" reference))) 2e-5)
                              "BERT masked-token loss")
                       (check (= (length gradients) (hash-table-count expected-gradients))
                              "BERT gradient coverage")
                       (dolist (entry gradients)
                         (close-arrays (tb:tensor-array (cdr entry))
                                       (tb:tensor-array (gethash (car entry) expected-gradients))
                                       4e-6 4e-4)))
                  (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)
                  (maphash (lambda (name value) (declare (ignore name)) (tb:dispose value))
                           expected-gradients))))
            (signals tb:shape-error
              (tb:loss-and-gradients model ids :attention-mask mask))
            (signals tb:shape-error
              (tb:loss-and-gradients model ids
                                     :labels (make-array '(2 5) :initial-element -100)
                                     :attention-mask mask))
            (let ((invalid (make-array '(2 5) :initial-contents
                                       '(("bad" -100 -100 -100 -100)
                                         (-100 -100 -100 -100 -100)))))
              (signals tb:shape-error
                (tb:loss-and-gradients model ids :labels invalid :attention-mask mask)))
            (let ((config (tb:model-config model)))
              (unwind-protect
                   (progn
                     (setf (gethash "hidden_dropout_prob" config) 0.1)
                     (signals tb:compatibility-error
                       (tb:loss-and-gradients model ids :labels labels :attention-mask mask)))
                (setf (gethash "hidden_dropout_prob" config) 0.0)))))
      (dolist (entry '(("is_decoder" . yason:true)
                       ("add_cross_attention" . yason:true)
                       ("tie_word_embeddings" . yason:false)
                       ("position_embedding_type" . "relative_key")
                       ("gradient_checkpointing" . yason:true)
                       ("new_encoder_scheme" . yason:true)))
        (let ((config (alexandria:copy-hash-table (tb:model-config model))))
          (setf (gethash (car entry) config) (cdr entry))
          (signals tb:compatibility-error (tb::validate-config config))))
      (let ((destination
              (merge-pathnames
               (format nil ".build/bert-export-~:[~;real-~]~(~A~)/" real device) root)))
        (tb:save-pretrained model destination)
        (check (probe-file (merge-pathnames "vocab.txt" destination))
               "BERT export preserves its WordPiece vocabulary")
        (tb:with-resource (reloaded (tb:from-pretrained destination :device device))
          (tb:with-resource (logits (tb:forward reloaded ids :attention-mask mask))
            (close-arrays (tb:tensor-array logits) expected atol 3e-4))))
      (unless real
        (tb:sgd-step model ids :labels labels :attention-mask mask :learning-rate 0.01)
        (tb:save-pretrained model
                            (merge-pathnames (format nil ".build/bert-updated-~(~A~)/" device) root)))))
  (unless (uiop:getenv "TB_BERT_REAL")
    (let ((root (asdf:system-source-directory "cl-transformer-blocks")))
      (dolist (entry '((".build/fixtures/bert-invalid-pretraining/" . "pretraining-only")
                       (".build/fixtures/bert-duplicate-layernorm/" . "legacy and canonical")))
        (check
         (handler-case
             (progn
               (tb:dispose (tb:from-pretrained (merge-pathnames (car entry) root)))
               nil)
           (tb:compatibility-error (condition)
             (search (cdr entry) (string-downcase (princ-to-string condition)))))
         "malformed historical BERT weights must be rejected")))
    (run-bert-lora-tests))
  (format t "BERT native acceptance tests passed.~%"))

(defun check-bert-adapter-variant (root device base adapter variant)
  (let* ((reference (tb::read-json (merge-pathnames "reference.json" adapter)))
         (ids (json-array (gethash "input_ids" reference)))
         (mask (json-array (gethash "attention_mask" reference)))
         (types (json-array (gethash "token_type_ids" reference)))
         (labels (json-array (gethash "labels" reference))))
    (tb:with-resource (model (tb:from-pretrained base :device device))
      (tb:load-adapter model adapter)
      (tb:with-resource (logits (tb:forward model ids :attention-mask mask :token-type-ids types))
        (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference))))
      (multiple-value-bind (loss gradients)
          (tb:loss-and-gradients model ids :labels labels :attention-mask mask :token-type-ids types)
        (let ((expected (make-hash-table :test 'equal)))
          (unwind-protect
               (progn
                 (tb::load-weights (merge-pathnames "gradients.safetensors" adapter)
                                   (tb:model-backend model) expected)
                 (check (< (abs (- loss (gethash "loss" reference))) 2e-5)
                        "BERT adapter masked-token loss")
                 (check (= (length gradients) (hash-table-count expected))
                        "only BERT adapter gradients")
                 (dolist (entry gradients)
                   (close-arrays (tb:tensor-array (cdr entry))
                                 (tb:tensor-array (gethash (car entry) expected))
                                 4e-6 4e-4)))
            (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)
            (maphash (lambda (name value) (declare (ignore name)) (tb:dispose value))
                     expected))))
      (tb:save-adapter
       model (merge-pathnames (format nil ".build/bert-~A-~(~A~)/" variant device) root))
      (tb:sgd-step model ids :labels labels :attention-mask mask :token-type-ids types :learning-rate 0.01)
      (tb:save-adapter
       model (merge-pathnames (format nil ".build/bert-~A-sgd-~(~A~)/" variant device) root)))
    (tb:with-resource (model (tb:from-pretrained base :device device))
      (tb:load-adapter model adapter)
      (tb:merge-adapter model)
      (tb:save-pretrained
       model (merge-pathnames (format nil ".build/bert-~A-merged-~(~A~)/" variant device) root)))))

(defun run-bert-lora-tests ()
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (base (merge-pathnames ".build/fixtures/bert/" root))
         (adapter (merge-pathnames ".build/fixtures/bert-lora/" root))
         (reference (tb::read-json (merge-pathnames "reference.json" adapter)))
         (ids (json-array (gethash "input_ids" reference)))
         (mask (json-array (gethash "attention_mask" reference))))
    (check-bert-adapter-variant root device base adapter "lora")
    (check-bert-adapter-variant root device base
                                (merge-pathnames ".build/fixtures/bert-rslora/" root)
                                "rslora")
    (tb:with-resource (model (tb:from-pretrained base :device device))
      (dolist (invalid '(("task_type" . "CAUSAL_LM")
                         ("target_modules" . #("q_proj"))))
        (let ((config (tb::read-json (merge-pathnames "adapter_config.json" adapter))))
          (setf (gethash (car invalid) config) (cdr invalid))
          (signals tb:compatibility-error (tb::validate-adapter model config))))
      (let* ((config (tb::read-json (merge-pathnames "adapter_config.json" adapter)))
             (mapping (gethash "auto_mapping" config)))
        (setf (gethash "base_model_class" mapping) "RemoteCustomModel")
        (signals tb:compatibility-error (tb::validate-adapter model config)))
      (signals tb:compatibility-error (tb:make-lora model :targets nil))
      (tb:with-resource (before (tb:forward model ids :attention-mask mask))
        (tb:make-lora model :rank 2 :alpha 4 :seed 53)
        (tb:with-resource (after (tb:forward model ids :attention-mask mask))
          (close-arrays (tb:tensor-array before) (tb:tensor-array after) 0 0)))
      (tb:save-adapter model
                       (merge-pathnames (format nil ".build/bert-lora-native-~(~A~)/" device) root)))
    (tb:with-resource (model (tb:from-pretrained base :device device))
      (tb:with-resource (before (tb:forward model ids :attention-mask mask))
        (tb:make-lora model :rank 3 :alpha 4 :rslora t :seed 59)
        (tb:with-resource (after (tb:forward model ids :attention-mask mask))
          (close-arrays (tb:tensor-array before) (tb:tensor-array after) 0 0)))
      (tb:save-adapter model
                       (merge-pathnames (format nil ".build/bert-rslora-native-~(~A~)/" device) root)))))
