(in-package #:tb-tests)

(defclass test-block-template () ())
(defmethod tb:component-config ((template test-block-template))
  (declare (ignore template))
  (tb:component-config
   (tb:make-transformer-block :attention (tb:make-rotary-attention :heads 4)
                             :feed-forward (tb:make-swiglu :intermediate-size 24))))

(defun run-component-tests ()
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (blocks (vector
                  (tb:make-transformer-block
                   :attention (tb:make-rotary-attention :heads 4 :kv-heads 2)
                   :feed-forward (tb:make-swiglu :intermediate-size 28)
                   :residual :sequential)
                  (tb:make-transformer-block
                   :attention (tb:make-rotary-attention :heads 2 :kv-heads 1 :rope-theta 5000.0)
                   :feed-forward (tb:make-swiglu :intermediate-size 36)
                   :norm-epsilon 2e-5 :residual :parallel)))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (directory (merge-pathnames (format nil ".build/components-created-~(~A~)/" device) root)))
    (signals tb:compatibility-error (tb:make-rotary-attention :heads 3 :kv-heads 2))
    (signals tb:compatibility-error (tb:make-swiglu :intermediate-size 0))
    (signals tb:compatibility-error
      (tb:make-transformer-block :attention (tb:make-rotary-attention :heads 4)
                                :feed-forward (tb:make-swiglu :intermediate-size 28)
                                :residual :unknown))
    (signals tb:compatibility-error
      (tb:make-transformer :vocab-size 32 :hidden-size 15 :blocks blocks :context-length 32))
    (signals tb:compatibility-error
      (tb:make-transformer :vocab-size 32 :hidden-size 16 :blocks #() :context-length 32))
    (tb:with-resource (custom (tb:make-transformer :vocab-size 32 :hidden-size 16
                              :blocks (list (make-instance 'test-block-template))
                              :context-length 32 :device device))
      (check (equal '(24 16) (tb:tensor-shape
                              (cdr (assoc "model.layers.0.mlp.up_proj.weight"
                                          (tb:named-parameters custom) :test #'equal))))
             "a user CLOS descriptor lowers into the portable block vocabulary"))
    (tb:with-resource (model (tb:make-transformer :vocab-size 32 :hidden-size 16 :blocks blocks
                                                 :context-length 32 :seed 104729 :device device))
      (check (= 2 (length (tb:transformer-blocks model))) "two composed blocks")
      (check (equal (gethash "model_type" (tb:model-config model)) "tb_composed")
             "composition has an explicit custom architecture identity")
      (check (= 20 (length (tb:named-parameters model)))
             "mixed residual schema includes the sequential block's second normalization")
      (let ((names (mapcar #'car (tb:named-parameters model))))
        (check (member "model.layers.0.post_attention_layernorm.weight" names :test #'equal)
               "sequential block owns its second normalization")
        (check (not (member "model.layers.1.post_attention_layernorm.weight" names :test #'equal))
               "parallel block shares its normalized input"))
      (setf (aref blocks 0) nil)
      (setf (aref (tb:transformer-blocks model) 0) nil)
      (check (typep (aref (tb:transformer-blocks model) 0) 'tb:transformer-block)
             "model snapshots the caller's component sequence")
      (signals tb:compatibility-error (tb:make-lora model))
      (let ((config (tb::copy-component-data (tb:model-config model))))
        (setf (gethash "architectures" config) #("tbcomposedforcausallm"))
        (signals tb:compatibility-error (tb::validate-config config)))
      (let* ((config (tb:model-config model))
             (first (aref (gethash "block_configs" config) 0)))
        (unwind-protect
             (progn
               (setf (gethash "residual" first) "parallel")
               (signals tb:compatibility-error (tb:forward model #2A((3 4))))
               (signals tb:compatibility-error
                 (tb:save-pretrained model (merge-pathnames "invalid-export/" directory))))
          (setf (gethash "residual" first) "sequential")))
      (let ((description (tb:component-config (aref (tb:transformer-blocks model) 0))))
        (setf (gethash "theta" (gethash "attention" description)) 1.0)
        (check (= 10000.0 (gethash "theta" (gethash "attention"
                            (tb:component-config (aref (tb:transformer-blocks model) 0)))))
               "component metadata is a deep snapshot"))
      (tb:save-pretrained model directory)
      (tb:save-pretrained model (merge-pathnames "sharded/" directory) :max-shard-size 1024)
      (tb:with-resource (again (tb:make-transformer
                               :vocab-size 32 :hidden-size 16 :blocks (tb:transformer-blocks model)
                               :context-length 32 :seed 104729 :device device))
        (loop for first in (tb:named-parameters model) for second in (tb:named-parameters again) do
          (close-arrays (tb:tensor-array (cdr first)) (tb:tensor-array (cdr second)) 0 0)))
      (tb:with-resource (full (tb:forward model #2A((3 4 5 6))))
        (let ((expected (tb:tensor-array full)))
          (tb:with-resource (cache (tb:make-cache model :growth-step 2))
            (tb:with-resource (prefix (tb:forward model #2A((3 4)) :cache cache))
              (dotimes (time 2) (dotimes (v 32)
                (check (< (abs (- (aref expected 0 time v)
                                 (aref (tb:tensor-array prefix) 0 time v))) 1e-5)
                       "cached prefix preserves logits"))))
            (tb:with-resource (suffix (tb:forward model #2A((5 6)) :cache cache))
              (dotimes (time 2) (dotimes (v 32)
                (check (< (abs (- (aref expected 0 (+ time 2) v)
                                 (aref (tb:tensor-array suffix) 0 time v))) 1e-5)
                       "heterogeneous-head cached suffix preserves logits"))))
            (check (= 4 (tb:cache-length cache)) "cache commits the complete prefix"))
          (tb:with-resource (changed (tb:forward model #2A((3 4 5 8))))
            (let ((actual (tb:tensor-array changed)))
              (dotimes (time 3) (dotimes (v 32)
                (check (= (aref actual 0 time v) (aref expected 0 time v))
                       "future token cannot alter past logits")))))))
      (let ((ids #2A((3 4 5 6) (7 5 4 3)))
            (mask #2A((1 1 1 0) (1 1 1 1)))
            (labels #2A((-100 4 5 -100) (-100 -100 4 3))))
        (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
          (check (equal '(2 4 32) (tb:tensor-shape logits)) "composed logits have task shape")
          (tb::save-weights (list (cons "logits" logits)) (merge-pathnames "native-logits.safetensors" directory)))
        (multiple-value-bind (loss gradients)
            (tb:loss-and-gradients model ids :labels labels :attention-mask mask)
          (unwind-protect
               (progn
                 (check (= 20 (length gradients)) "every composed parameter is differentiated")
                 (tb::write-json (let ((h (make-hash-table :test 'equal)))
                                   (setf (gethash "loss" h) loss) h)
                                 (merge-pathnames "native-loss.json" directory))
                 (tb::save-weights gradients (merge-pathnames "native-gradients.safetensors" directory)))
            (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)))
        (tb:sgd-step model ids :labels labels :attention-mask mask :learning-rate 0.01)
        (tb:save-pretrained model (merge-pathnames "updated/" directory)))
      (tb:with-resource (tied (tb:make-transformer :vocab-size 32 :hidden-size 16
                              :blocks (tb:transformer-blocks model) :context-length 32
                              :tie-word-embeddings t :seed 104729 :device device))
        (check (= 19 (length (tb:named-parameters tied))) "tied head is one canonical parameter")
        (tb:save-pretrained tied (merge-pathnames "tied/" directory))
        (multiple-value-bind (loss gradients) (tb:loss-and-gradients tied #2A((3 4 5 6)))
          (declare (ignore loss))
          (unwind-protect
               (progn (check (= 19 (length gradients)) "tied gradient has no duplicated head")
                      (tb::save-weights gradients (merge-pathnames "tied/native-gradients.safetensors" directory)))
            (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients))))
      (format t "~&Component construction tests passed: ~A~%" device))))

(defun run-component-roundtrip-tests ()
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (directory (merge-pathnames (format nil ".build/components-created-~(~A~)/" device) root))
         (source (merge-pathnames "python-updated/" directory))
         (reference (tb::read-json (merge-pathnames "reference.json" source)))
         (ids #2A((3 4 5 6) (7 5 4 3)))
         (mask #2A((1 1 1 0) (1 1 1 1)))
         (checkpoint (merge-pathnames "native-resume/" directory)))
    (tb:with-resource (model (tb:from-pretrained source :device device))
      (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
        (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference)) 2e-6 3e-4))
      (check (equalp (tb:generate model #(3 4) :max-new-tokens 4 :eos-token-id nil)
                     (gethash "generated" reference)) "Python and Lisp greedy generation agree")
      (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001))
        (tb:train-step model optimizer ids :attention-mask mask)
        (tb:save-training-checkpoint model optimizer checkpoint)
        (tb:with-resource (restored (tb:from-pretrained checkpoint :device device))
          (tb:with-resource (next-optimizer (tb:make-adamw :learning-rate 0.001))
            (check (= 1 (tb:restore-training-checkpoint restored next-optimizer checkpoint))
                   "composed optimizer checkpoint restores its step")
            (check (= (tb:train-step model optimizer ids :attention-mask mask)
                       (tb:train-step restored next-optimizer ids :attention-mask mask))
                   "resumed composed training loss is exact")
            (loop for first in (tb:named-parameters model) for second in (tb:named-parameters restored) do
              (close-arrays (tb:tensor-array (cdr first)) (tb:tensor-array (cdr second)) 0 0))))))
    (format t "~&Python-to-Lisp composed round trip passed: ~A~%" device)))
