(in-package #:tb-tests)

(defun component-lora-optimizer (algorithm)
  (ecase algorithm
    (:sgd (tb:make-sgd :learning-rate 0.01 :momentum 0.9 :weight-decay 0.02))
    (:adamw (tb:make-adamw :learning-rate 0.001 :beta1 0.8 :beta2 0.95 :weight-decay 0.02))))

(defun component-lora-import (base folder device ids mask labels reference)
  (tb:with-resource (model (tb:from-pretrained base :device device))
    (tb:load-adapter model folder)
    (check (= 28 (length (tb:trainable-parameters model)))
           "seven projections in both blocks expose all A/B factors")
    (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
      (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference)) 2e-6 3e-4)
      (tb::save-weights (list (cons "logits" logits)) (merge-pathnames "native-logits.safetensors" folder)))
    (multiple-value-bind (loss gradients)
        (tb:loss-and-gradients model ids :labels labels :attention-mask mask)
      (let ((expected (make-hash-table :test 'equal)))
        (unwind-protect
             (progn
               (check (< (abs (- loss (gethash "loss" reference))) 2e-6) "composed PEFT masked loss")
               (tb::load-weights (merge-pathnames "gradients.safetensors" folder)
                                (tb:model-backend model) expected)
               (check (= 28 (length gradients) (hash-table-count expected)) "complete adapter gradient coverage")
               (dolist (entry gradients)
                 (close-arrays (tb:tensor-array (cdr entry))
                               (tb:tensor-array (gethash (car entry) expected)) 2e-6 3e-4))
               (tb::save-weights gradients (merge-pathnames "native-gradients.safetensors" folder)))
          (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)
          (maphash (lambda (key tensor) (declare (ignore key)) (tb:dispose tensor)) expected))))
    (signals tb:compatibility-error (tb:save-pretrained model (merge-pathnames "invalid/" folder)))
    (tb:save-adapter model (merge-pathnames "native-exported/" folder))
    (tb:merge-adapter model)
    (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
      (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference)) 2e-6 3e-4))
    (tb:save-pretrained model (merge-pathnames "merged/" folder))))

(defun component-lora-training (base folder device ids mask labels reference algorithm)
  (let ((checkpoint (merge-pathnames (format nil "~(~A~)-resume/" algorithm) folder)))
    (tb:with-resource (model (tb:from-pretrained base :device device))
      (tb:load-adapter model folder)
      (let ((original (mapcar (lambda (entry) (cons (car entry) (tb:tensor-array (cdr entry))))
                             (tb:named-parameters model))))
        (tb:with-resource (optimizer (component-lora-optimizer algorithm))
          (dotimes (index 2)
            (check (< (abs (- (tb:train-step model optimizer ids :labels labels :attention-mask mask
                                            :max-grad-norm 0.05)
                              (aref (gethash (string-downcase (symbol-name algorithm)) reference) index))) 2e-6)
                   "composed adapter matches Python optimizer loss trajectory"))
          (tb:save-training-checkpoint model optimizer checkpoint)
          (tb:with-resource (resumed (tb:from-pretrained base :device device))
            (tb:load-adapter resumed checkpoint)
            (tb:with-resource (next (component-lora-optimizer algorithm))
              (check (= 2 (tb:restore-training-checkpoint resumed next checkpoint))
                     "composed adapter checkpoint restores its step")
              (let ((loss (tb:train-step model optimizer ids :labels labels :attention-mask mask
                                         :max-grad-norm 0.05)))
                (check (= loss (tb:train-step resumed next ids :labels labels :attention-mask mask
                                             :max-grad-norm 0.05))
                       "resumed adapter loss is exact")
                (check (< (abs (- loss (aref (gethash (string-downcase (symbol-name algorithm)) reference) 2)))
                          2e-6) "third loss matches Python"))
              (loop for a in (tb:trainable-parameters model) for b in (tb:trainable-parameters resumed) do
                (check (equal (car a) (car b)) "resumed adapter names agree")
                (close-arrays (tb:tensor-array (cdr a)) (tb:tensor-array (cdr b)) 0 0)))))
        (dolist (entry original)
          (close-arrays (cdr entry)
                        (tb:tensor-array (cdr (assoc (car entry) (tb:named-parameters model) :test #'equal))) 0 0))
        (tb:save-adapter model (merge-pathnames (format nil "native-~(~A~)/" algorithm) folder))))))

(defun component-lora-created (base folder device ids mask labels variant)
  (tb:with-resource (model (tb:from-pretrained base :device device))
    (signals tb:compatibility-error (tb:make-lora model :targets '("lm_head")))
    (let* ((description (aref (gethash "block_configs" (tb:model-config model)) 0))
           (epsilon (gethash "rms_norm_eps" description)))
      (unwind-protect
           (progn
             (setf (gethash "rms_norm_eps" description) 0.1)
             (signals tb:compatibility-error (tb:make-lora model)))
        (setf (gethash "rms_norm_eps" description) epsilon)))
    (tb:with-resource (stale (tb:make-cache model))
      (tb:with-resource (before (tb:forward model ids :attention-mask mask))
        (tb:make-lora model :rank 3 :alpha 6 :rslora (equal variant "rslora") :seed 37
                      :targets '("q_proj" "k_proj" "v_proj" "o_proj" "gate_proj" "up_proj" "down_proj"))
        (tb:with-resource (after (tb:forward model ids :attention-mask mask))
          (close-arrays (tb:tensor-array before) (tb:tensor-array after) 0 0)))
      (signals tb:compatibility-error (tb:forward model #2A((3 4)) :cache stale)))
    (tb:with-resource (cache (tb:make-cache model))
      (tb:with-resource (prefix (tb:forward model #2A((3 4)) :cache cache))
        (check (= 2 (second (tb:tensor-shape prefix))) "adapter cache starts normally"))
      (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001))
        (dotimes (step 4) (tb:train-step model optimizer ids :labels labels :attention-mask mask)))
      (signals tb:compatibility-error (tb:forward model #2A((5 6)) :cache cache)))
    ;; Test chunked cache after nonzero adapter training, with different layer head shapes.
    (tb:with-resource (full (tb:forward model #2A((3 4 5 6))))
      (tb:with-resource (cache (tb:make-cache model :growth-step 2))
        (tb:with-resource (prefix (tb:forward model #2A((3 4)) :cache cache))
          (check (= 2 (second (tb:tensor-shape prefix))) "trained adapter prefill"))
        (tb:with-resource (suffix (tb:forward model #2A((5 6)) :cache cache))
          (let ((expected (tb:tensor-array full)) (actual (tb:tensor-array suffix)))
            (dotimes (time 2) (dotimes (v 32)
              (check (< (abs (- (aref expected 0 (+ time 2) v) (aref actual 0 time v))) 2e-6)
                     "trained heterogeneous adapter cached suffix matches full forward")))))))
    (tb:save-adapter model (merge-pathnames "created/" folder))
    (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
      (tb::save-weights (list (cons "logits" logits)) (merge-pathnames "created-logits.safetensors" folder)))
    (tb::write-json (tb:generate model #(3 4) :max-new-tokens 4 :eos-token-id nil)
                    (merge-pathnames "created-generation.json" folder))))

(defun run-component-lora-tests ()
  (tb::ensure-native)
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (directory (merge-pathnames (format nil ".build/components-created-~(~A~)/" device) root))
         (handles (tb::%tb-live-tensors)))
    (tb:with-resource (model (tb:from-pretrained directory :device device))
      (tb:make-lora model :rank 3 :alpha 6)
      (check (= 8 (length (tb:trainable-parameters model)))
             "composed models expose default query/value LoRA factors"))
    (check (every (lambda (op) (member op (getf (tb:inspect-pretrained directory) :operations)))
                  '(:lora :rslora)) "composed adapter capabilities are discoverable")
    (dolist (kind '("untied" "tied"))
      (let ((base (if (equal kind "tied") (merge-pathnames "tied/" directory) directory)))
        (dolist (variant '("standard" "rslora"))
          (let* ((folder (merge-pathnames (format nil "lora/~A/~A/" kind variant) directory))
                 (reference (tb::read-json (merge-pathnames "reference.json" folder)))
                 (ids (json-array (gethash "input_ids" reference)))
                 (mask (json-array (gethash "attention_mask" reference)))
                 (labels (json-array (gethash "labels" reference))))
            (component-lora-import base folder device ids mask labels reference)
            (dolist (algorithm '(:sgd :adamw))
              (component-lora-training base folder device ids mask labels reference algorithm))
            (component-lora-created base folder device ids mask labels variant)))))
    (check (= handles (tb::%tb-live-tensors)) "composed adapters and optimizer state release all tensor handles")
    (format t "~&Composed LoRA/rsLoRA native gates passed: ~A (~D checks).~%" device *checks*)))

(defun run-component-lora-roundtrip-tests ()
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (directory (merge-pathnames (format nil ".build/components-created-~(~A~)/" device) root)))
    (dolist (kind '("untied" "tied"))
      (let ((base (if (equal kind "tied") (merge-pathnames "tied/" directory) directory)))
        (dolist (variant '("standard" "rslora"))
          (let* ((folder (merge-pathnames (format nil "lora/~A/~A/" kind variant) directory))
                 (inputs (tb::read-json (merge-pathnames "reference.json" folder)))
                 (continued (merge-pathnames "python-continued/" folder))
                 (expected (tb::read-json (merge-pathnames "reference.json" continued)))
                 (ids (json-array (gethash "input_ids" inputs)))
                 (mask (json-array (gethash "attention_mask" inputs))))
            (tb:with-resource (model (tb:from-pretrained base :device device))
              (tb:load-adapter model continued)
              (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
                (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" expected)) 2e-6 3e-4))
              (multiple-value-bind (loss gradients)
                  (tb:loss-and-gradients model ids :attention-mask mask
                                         :labels (json-array (gethash "labels" inputs)))
                (unwind-protect
                     (progn
                       (check (< (abs (- loss (gethash "loss" expected))) 2e-6)
                              "Python continuation returns the same masked loss to Lisp")
                       (check (= 28 (length gradients)) "returned adapter remains trainable in Lisp"))
                  (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients))))))))
    (format t "~&Lisp-created adapters trained in Python and reloaded in Lisp: ~A (~D checks).~%"
            device *checks*)))
