(in-package #:tb-tests)

(defclass unqualified-llama (tb::llama-model) ())

(defun check-composition-rejections (source destination)
  (let ((config (tb:model-config source)))
    (dolist (pair '(("head_dim" . 8) ("attention_bias" . yason:true)
                    ("num_hidden_layers" . 3) ("architectures" . #("OtherForCausalLM"))))
      (multiple-value-bind (old present) (gethash (car pair) config)
        (unwind-protect
             (progn (setf (gethash (car pair) config) (cdr pair))
                    (signals tb:compatibility-error (tb:save-composed-pretrained source destination)))
          (if present (setf (gethash (car pair) config) old) (remhash (car pair) config))))))
  (unwind-protect
       (progn (change-class source 'unqualified-llama)
              (signals tb:compatibility-error (tb:save-composed-pretrained source destination)))
    (change-class source 'tb::llama-model))
  (signals tb:shape-error (tb:save-composed-pretrained source destination :max-shard-size 0))
  (signals tb:compatibility-error (tb:save-composed-pretrained source (tb::model-directory source)))
  (tb:make-lora source :rank 2 :alpha 4)
  (signals tb:compatibility-error (tb:save-composed-pretrained source destination))
  (tb:remove-adapter source)
  (let* ((table (tb::parameters source))
         (name "model.norm.weight") (weight (gethash name table)))
    (unwind-protect
         (progn (remhash name table)
                (signals tb:compatibility-error (tb:save-composed-pretrained source destination)))
      (setf (gethash name table) weight))
    (unwind-protect
         (progn (setf (gethash "unexpected.weight" table) weight)
                (signals tb:compatibility-error (tb:save-composed-pretrained source destination)))
      (remhash "unexpected.weight" table))
    (tb:with-resource (wrong (tb:tensor-from-array (tb:model-backend source) #(1.0)))
      (unwind-protect
           (progn (setf (gethash name table) wrong)
                  (signals tb:shape-error (tb:save-composed-pretrained source destination)))
        (setf (gethash name table) weight)))))

(defun composition-check-training (model reference directory)
  (let ((ids (json-array (gethash "input_ids" reference)))
        (mask (json-array (gethash "attention_mask" reference)))
        (labels (json-array (gethash "labels" reference))))
    (multiple-value-bind (loss gradients)
        (tb:loss-and-gradients model ids :attention-mask mask :labels labels)
      (unwind-protect
           (progn
             (check (< (abs (- loss (gethash "loss" reference))) 2e-6) "converted independent masked loss")
             (check (= (length gradients) (length (tb:named-parameters model))) "complete converted gradient coverage")
             (tb::save-weights gradients (merge-pathnames "native-gradients.safetensors" directory)))
        (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)))
    (tb:sgd-step model ids :attention-mask mask :labels labels :learning-rate 0.01)
    (tb:save-pretrained model (merge-pathnames "updated/" directory))))

(defun composition-check-adapter (model reference directory)
  (let ((ids (json-array (gethash "input_ids" reference)))
        (mask (json-array (gethash "attention_mask" reference))))
    (tb:make-lora model :rank 2 :alpha 4 :seed 37)
    (check (= (* 4 (length (tb:transformer-blocks model))) (length (tb:trainable-parameters model)))
           "converted pretrained blocks expose query/value adapter factors")
    (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001))
      (tb:train-step model optimizer ids :attention-mask mask
                     :labels (json-array (gethash "labels" reference)) :max-grad-norm 1.0))
    (tb:save-adapter model (merge-pathnames "adapter/" directory))
    (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
      (tb::save-weights (list (cons "logits" logits)) (merge-pathnames "adapter-logits.safetensors" directory)))
    (tb:remove-adapter model)))

(defun run-composition-import-tests ()
  (tb::ensure-native)
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (real (equal (uiop:getenv "TB_COMPOSITION_REAL") "1"))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (output (merge-pathnames (format nil ".build/composition-import-~(~A~)/" device) root))
         (baseline-handles (tb::%tb-live-tensors)))
    (dolist (name (if real '("real") '("tied" "untied" "mha" "mqa")))
      (let* ((base (merge-pathnames (if real ".build/models/smollm2/"
                                      (format nil ".build/fixtures/composition-import/~A/" name)) root))
             (destination (merge-pathnames (format nil "~A/" name) output))
             (reference (tb::read-json (merge-pathnames (format nil "~A-reference.json" name) output)))
             (ids (json-array (gethash "input_ids" reference)))
             (mask (json-array (gethash "attention_mask" reference)))
             (source-logits nil) (source-tokens nil)
             (generation-source (uiop:read-file-string (merge-pathnames "generation_config.json" base))))
        (tb:with-resource (source (tb:from-pretrained base :device device))
          (let ((configuration (tb::copy-component-data (tb:model-config source))))
            (unless real (check-composition-rejections source destination))
            (when (equal name "tied") (tb:attach-tokenizer source base))
            (tb:with-resource (before (tb:forward source ids :attention-mask mask))
              (setf source-logits (tb:tensor-array before)))
            (setf source-tokens (tb:generate source #(3 4) :max-new-tokens 4 :eos-token-id nil))
            (let ((handles (tb::%tb-live-tensors)))
              (tb:save-composed-pretrained source destination :max-shard-size (if real 16777216 1024))
              (check (= handles (tb::%tb-live-tensors)) "conversion borrows weights without leaking handles"))
            (check (tb::same-component-data-p configuration (tb:model-config source)) "source configuration stays unchanged")
            (tb:with-resource (after (tb:forward source ids :attention-mask mask))
              (close-arrays source-logits (tb:tensor-array after) 0 0))
            (check (equal generation-source (uiop:read-file-string (merge-pathnames "generation_config.json" base)))
                   "source generation settings stay unchanged")
            (when (equal name "tied")
              (let ((sentinel (merge-pathnames "previous-export" destination)))
                (with-open-file (stream sentinel :direction :output :if-exists :supersede)
                  (write-string "previous complete conversion" stream))
                (let ((tb::*before-directory-publication*
                        (lambda (stage published) (declare (ignore stage published)) (error "injected conversion publication failure"))))
                  (signals error (tb:save-composed-pretrained source destination)))
                (check (equal (uiop:read-file-string sentinel) "previous complete conversion")
                       "failed conversion preserves prior output")
                (tb:save-composed-pretrained source destination :max-shard-size 1024)
                (check (not (probe-file sentinel)) "conversion replaces the entire output")))
            (when (equal name "tied")
              (tb:sgd-step source ids :attention-mask mask
                           :labels (json-array (gethash "labels" reference)) :learning-rate 0.01)
              (tb:save-composed-pretrained source (merge-pathnames "updated-source/" destination)))))
        ;; Reload only after disposing the source: the result is an independent artifact.
        (tb:with-resource (converted (tb:from-pretrained destination :device device))
          (check (typep converted 'tb:composed-causal-lm) "pretrained weights load as public Lisp components")
          (check (= (length (tb:transformer-blocks converted)) (gethash "num_hidden_layers" (tb:model-config converted)))
                 "every pretrained block is publicly inspectable")
          (signals tb:compatibility-error (tb:save-composed-pretrained converted (merge-pathnames "unsupported/" output)))
          (tb:with-resource (after (tb:forward converted ids :attention-mask mask))
            (close-arrays (tb:tensor-array after) source-logits (if real 1e-3 2e-6) 3e-4)
            (close-arrays (tb:tensor-array after) (json-array (gethash "logits" reference)) (if real 1e-3 2e-6) 3e-4)
            (tb::save-weights (list (cons "logits" after)) (merge-pathnames "native-logits.safetensors" destination)))
          (check (equalp (tb:encode-text converted (gethash "text" reference) :add-special-tokens nil)
                         (gethash "tokens" reference)) "converted tokenizer IDs match Python")
          (let ((tokens (tb:generate converted #(3 4) :max-new-tokens 4 :eos-token-id nil)))
            (check (equalp tokens source-tokens) "converted cached generation matches the source")
            (tb::write-json tokens (merge-pathnames "native-generation.json" destination)))
          (composition-check-adapter converted reference destination)
          (unless real (composition-check-training converted reference destination)))))
    (check (= baseline-handles (tb::%tb-live-tensors)) "conversion/reload/training releases all tensor handles")
    (format t "~&Pretrained-to-component native gates passed: ~A, real=~S (~D checks).~%" device real *checks*)))

(defun run-composition-import-roundtrip-tests ()
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (output (merge-pathnames (format nil ".build/composition-import-~(~A~)/" device) root)))
    (dolist (name '("tied" "untied" "mha" "mqa"))
      (let* ((directory (merge-pathnames (format nil "~A/python-continued/" name) output))
             (inputs (tb::read-json (merge-pathnames (format nil "~A-reference.json" name) output)))
             (reference (tb::read-json (merge-pathnames "reference.json" directory)))
             (ids (json-array (gethash "input_ids" inputs)))
             (mask (json-array (gethash "attention_mask" inputs))))
        (tb:with-resource (model (tb:from-pretrained directory :device device))
          (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
            (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference)) 2e-6 3e-4))
          (multiple-value-bind (loss gradients)
              (tb:loss-and-gradients model ids :attention-mask mask :labels (json-array (gethash "labels" inputs)))
            (unwind-protect
                 (check (< (abs (- loss (gethash "loss" reference))) 2e-6) "Python-trained conversion returns matching loss to Lisp")
              (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients))))))
    (format t "~&Python-trained component conversions reloaded in Lisp: ~A (~D checks).~%" device *checks*)))
