(in-package #:tb-tests)

(defun distillation-optimizer ()
  (tb:make-sgd :learning-rate 0.01 :momentum 0.9 :weight-decay 0.02))

(defun check-distillation-rejections (student teacher ids mask labels)
  (signals tb:compatibility-error (tb:distillation-loss-and-gradients student student ids))
  (signals tb:compatibility-error (tb:distillation-loss-and-gradients student nil ids))
  (dolist (temperature '(0 -1 "2"))
    (signals tb:shape-error (tb:distillation-loss-and-gradients student teacher ids :temperature temperature)))
  (dolist (weight '(-0.1 1.1 "0"))
    (signals tb:shape-error (tb:distillation-loss-and-gradients student teacher ids :hard-weight weight)))
  (signals tb:shape-error (tb:distillation-loss-and-gradients student teacher ids :labels #2A((1))))
  (signals tb:shape-error (tb:distillation-loss-and-gradients student teacher ids
                           :labels (make-array (array-dimensions ids) :initial-element -100)))
  (signals tb:shape-error (tb:distillation-loss-and-gradients student teacher ids
                           :attention-mask (make-array (array-dimensions ids) :initial-element 0)))
  (tb:with-resource (optimizer (distillation-optimizer))
    (signals tb:shape-error (tb:distill-step student teacher optimizer ids :max-grad-norm -1))
    (check (= 0 (tb::optimizer-step optimizer)) "invalid distillation leaves optimizer unbound")
    ;; A rejected batch must not change the student or optimizer state.
    (let ((version (tb::model-version student)))
      (signals tb:shape-error (tb:distill-step student teacher optimizer ids :labels #2A((1))))
      (check (= version (tb::model-version student)) "invalid batches leave student unchanged")))
  (multiple-value-bind (ordinary gradients) (tb:loss-and-gradients student ids :labels labels :attention-mask mask)
    (unwind-protect
         (multiple-value-bind (hard other)
             (tb:distillation-loss-and-gradients student teacher ids :labels labels :attention-mask mask :hard-weight 1)
           (unwind-protect
                (progn (check (= ordinary hard) "hard-weight one is ordinary cross entropy exactly")
                       (loop for a in gradients for b in other do
                         (check (equal (car a) (car b)) "hard objective gradient names")
                         (close-arrays (tb:tensor-array (cdr a)) (tb:tensor-array (cdr b)) 0 0)))
             (mapc (lambda (entry) (tb:dispose (cdr entry))) other)))
      (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients))))

(defun check-distillation-roundtrip (entry device tolerance)
  (let* ((folder (pathname (gethash "folder" entry)))
         (adapter (eq (gethash "adapter" entry) 'yason:true))
         (continued (merge-pathnames "python-continued/" folder)))
    (tb:with-resource (model (tb:from-pretrained (if adapter (gethash "student" entry) continued) :device device))
      (when adapter (tb:load-adapter model continued))
      (tb:with-resource (logits (tb:forward model (json-array (gethash "input_ids" entry))
                                          :attention-mask (json-array (gethash "attention_mask" entry))))
        (let ((expected (make-hash-table :test 'equal)))
          (unwind-protect
               (progn (tb::load-weights (merge-pathnames "python-logits.safetensors" folder)
                                        (tb:model-backend model) expected)
                      (close-arrays (tb:tensor-array logits) (tb:tensor-array (gethash "logits" expected)) tolerance 3e-4))
            (maphash (lambda (key value) (declare (ignore key)) (tb:dispose value)) expected)))))))

(defun run-distillation-tests ()
  (tb::ensure-native)
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (real (equal (uiop:getenv "TB_DISTILLATION_REAL") "1"))
         (roundtrip (equal (uiop:getenv "TB_DISTILLATION_ROUNDTRIP") "1"))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (manifest (tb::read-json (merge-pathnames (format nil ".build/distillation-~(~A~)/~Acases.json"
                                                           device (if real "real-" "")) root)))
         (tolerance (if real 1e-3 2e-6))
         (handles (tb::%tb-live-tensors)))
    (loop for entry across manifest do
      (if roundtrip (check-distillation-roundtrip entry device tolerance)
          (let* ((ids (json-array (gethash "input_ids" entry)))
                 (mask (json-array (gethash "attention_mask" entry)))
                 (labels (json-array (gethash "labels" entry)))
                 (folder (pathname (gethash "folder" entry)))
                 (adapter (eq (gethash "adapter" entry) 'yason:true))
                 (options (list :labels labels :attention-mask mask :temperature (gethash "temperature" entry)
                                :hard-weight (gethash "hard_weight" entry)))
                 (checkpoint (merge-pathnames "resume/" folder)))
            (tb:with-resource (teacher (tb:from-pretrained (gethash "teacher" entry) :device device))
              (tb:with-resource (student (tb:from-pretrained (gethash "student" entry) :device device))
                (dolist (model (list student teacher))
                  (check (member :distillation (getf (tb:model-capabilities model) :operations))
                         "qualified models advertise distillation"))
                (when adapter (tb:load-adapter student (merge-pathnames "initial-adapter/" folder)))
                (unless real (check-distillation-rejections student teacher ids mask labels))
                (let ((teacher-parameters (tb:named-parameters teacher))
                      (teacher-version (tb::model-version teacher))
                      (base (when adapter (tb:named-parameters student))))
                  (tb:with-resource (before (tb:forward teacher ids :attention-mask mask))
                    (multiple-value-bind (loss gradients)
                        (apply #'tb:distillation-loss-and-gradients student teacher ids options)
                      (unwind-protect
                           (progn
                             (check (< (abs (- loss (aref (gethash "losses" entry) 0))) tolerance)
                                    "distillation loss matches independent Torch KL and CE")
                             (check (= (length gradients) (length (tb:trainable-parameters student)))
                                    "every trainable student tensor receives a gradient")
                             (tb::save-weights gradients (merge-pathnames "native-gradients.safetensors" folder)))
                        (mapc (lambda (pair) (tb:dispose (cdr pair))) gradients)))
                    (tb:with-resource (optimizer (distillation-optimizer))
                      (tb:with-resource (stale (tb:make-cache student))
                        (tb:with-resource (out (tb:forward student #2A((3 4)) :cache stale)))
                        (dotimes (step 2)
                          (check (< (abs (- (apply #'tb:distill-step student teacher optimizer ids
                                                  :max-grad-norm 0.05 options)
                                           (aref (gethash "losses" entry) step))) tolerance)
                                 "clipped momentum SGD distillation trajectory matches Python"))
                        (signals tb:compatibility-error (tb:forward student #2A((3 4)) :cache stale)))
                      (tb:save-training-checkpoint student optimizer checkpoint)
                      (tb:with-resource (restored (tb:from-pretrained (if adapter (gethash "student" entry) checkpoint)
                                                                    :device device))
                        (when adapter (tb:load-adapter restored checkpoint))
                        (tb:with-resource (next (distillation-optimizer))
                          (check (= 2 (tb:restore-training-checkpoint restored next checkpoint)) "distillation optimizer restores step")
                          (let ((loss (apply #'tb:distill-step student teacher optimizer ids :max-grad-norm 0.05 options)))
                            (check (= loss (apply #'tb:distill-step restored teacher next ids :max-grad-norm 0.05 options))
                                   "resumed distillation loss is exact")
                            (check (< (abs (- loss (aref (gethash "losses" entry) 2))) tolerance) "third update loss matches Python"))
                          (loop for a in (tb:trainable-parameters student) for b in (tb:trainable-parameters restored) do
                            (check (equal (car a) (car b)) "resumed trainable names")
                            (close-arrays (tb:tensor-array (cdr a)) (tb:tensor-array (cdr b)) 0 0)))))
                    (check (= teacher-version (tb::model-version teacher)) "teacher version stays frozen")
                    (loop for a in teacher-parameters for b in (tb:named-parameters teacher) do
                      (check (and (equal (car a) (car b)) (eq (cdr a) (cdr b))) "teacher parameter bindings stay frozen"))
                    (when adapter
                      (loop for a in base for b in (tb:named-parameters student) do
                        (check (eq (cdr a) (cdr b)) "student base stays frozen during adapter distillation")))
                    (tb:with-resource (after (tb:forward teacher ids :attention-mask mask))
                      (close-arrays (tb:tensor-array before) (tb:tensor-array after) 0 0)))
                  (if adapter (tb:save-adapter student (merge-pathnames "exported/" folder))
                      (tb:save-pretrained student (merge-pathnames "exported/" folder)))
                  (tb:with-resource (logits (tb:forward student ids :attention-mask mask))
                    (tb::save-weights (list (cons "logits" logits)) (merge-pathnames "native-logits.safetensors" folder)))))))))
    (check (= handles (tb::%tb-live-tensors)) "distillation teacher/student/gradient handles are released")
    (format t "~&Distillation passed: ~A, real=~S, roundtrip=~S (~D checks).~%" device real roundtrip *checks*)))
