(in-package #:tb-tests)
(defun run-gpt2-tests ()
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (real (uiop:getenv "TB_GPT2_REAL"))
         (variants (if real '("distilgpt2") '("standard" "untied" "scaling" "gelu" "legacy"))))
    (dolist (variant variants)
      (let* ((folder (merge-pathnames (if real ".build/models/distilgpt2/" (format nil ".build/fixtures/gpt2/~A/" variant)) root))
             (ref (tb::read-json (merge-pathnames "reference.json" folder)))
             (ids (json-array (gethash "input_ids" ref))) (mask (json-array (gethash "attention_mask" ref)))
             (labels (json-array (gethash "labels" ref))) (expected (json-array (gethash "logits" ref)))
             (atol (if real 1e-3 3e-5)))
        (let* ((capabilities (tb:inspect-pretrained folder))
               (operations (getf capabilities :operations)))
          (check (eq (getf capabilities :architecture) :gpt2)
                 "GPT-2 architecture is discoverable")
          (check (every (lambda (operation) (member operation operations))
                        '(:forward :export :cache :generation))
                 "GPT-2 inference operations are discoverable")
          (check (eq (not real) (not (null (member :training operations))))
                 "GPT-2 training capability follows configured dropout")
          (check (eq (not real) (not (null (member :training-checkpoint operations))))
                 "GPT-2 checkpoint capability follows configured dropout")
          (check (not (member :lora operations)) "unsupported GPT-2 PEFT is absent"))
        (tb:with-resource (model (tb:from-pretrained folder :device device))
          (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
            (format t "~&GPT-2 ~A ~A max error: ~E~%" variant device (close-arrays (tb:tensor-array logits) expected atol 3e-4)))
          (tb:with-resource (cache (tb:make-cache model))
            (dotimes (position 4)
              (let ((step (make-array '(2 1))) (padding (make-array (list 2 (1+ position)))))
                (dotimes (b 2)
                  (setf (aref step b 0) (aref ids b position))
                  (dotimes (i (1+ position)) (setf (aref padding b i) (aref mask b i))))
                (tb:with-resource (logits (tb:forward model step :cache cache :attention-mask padding))
                  (let* ((actual (tb:tensor-array logits)) (slice (make-array (array-dimensions actual))))
                    (dotimes (b 2) (dotimes (v (array-dimension expected 2)) (setf (aref slice b 0 v) (aref expected b position v))))
                    (close-arrays actual slice atol 3e-4))))))
          (check (equalp (tb:generate model #(3 4) :max-new-tokens 4 :eos-token-id nil) (gethash "generated" ref)) "GPT-2 greedy generation")
          (let* ((tokenizer (tb::read-json (merge-pathnames "tokenizer-reference.json" folder)))
                 (encoded (tb:encode-text model (gethash "text" tokenizer) :add-special-tokens nil)))
            (check (equalp encoded (gethash "ids" tokenizer)) "GPT-2 tokenizer IDs")
            (check (equal (tb:decode-tokens model encoded) (gethash "decoded" tokenizer)) "GPT-2 tokenizer decode"))
          (signals tb:shape-error (tb:forward model (make-array (list 1 (1+ (gethash "n_positions" (tb:model-config model)))) :initial-element 3)))
          (signals tb:compatibility-error (tb:make-lora model))
          (let ((c (alexandria:copy-hash-table (tb:model-config model))))
            (setf (gethash "add_cross_attention" c) 'yason:true)
            (signals tb:compatibility-error (tb::validate-config c)))
          (tb:save-pretrained model (merge-pathnames (format nil ".build/gpt2-export-~A-~(~A~)/" variant device) root))
          (if real
              (signals tb:compatibility-error (tb:loss-and-gradients model ids :labels labels :attention-mask mask))
              (progn
                (multiple-value-bind (loss gradients) (tb:loss-and-gradients model ids :labels labels :attention-mask mask)
                  (let ((expected-gradients (make-hash-table :test 'equal)))
                    (unwind-protect
                         (progn
                           (tb::load-weights (merge-pathnames "gradients.safetensors" folder) (tb:model-backend model) expected-gradients)
                           (check (< (abs (- loss (gethash "loss" ref))) 2e-5) "GPT-2 masked loss")
                           (check (= (length gradients) (hash-table-count expected-gradients)) "GPT-2 gradient coverage")
                           (dolist (entry gradients) (close-arrays (tb:tensor-array (cdr entry)) (tb:tensor-array (gethash (car entry) expected-gradients)) 3e-6 3e-4)))
                      (mapc (lambda (p) (tb:dispose (cdr p))) gradients)
                      (maphash (lambda (k v) (declare (ignore k)) (tb:dispose v)) expected-gradients))))
                (tb:sgd-step model ids :labels labels :attention-mask mask :learning-rate 0.01)
                (tb:save-pretrained model (merge-pathnames (format nil ".build/gpt2-updated-~A-~(~A~)/" variant device) root))))))))
  (unless (uiop:getenv "TB_GPT2_REAL")
    (check (handler-case (progn (tb:dispose (tb:from-pretrained ".build/fixtures/gpt2/bad-index/")) nil)
             (tb:compatibility-error (c) (search "shard" (princ-to-string c))))
           "index must match the shard that actually contains each tensor")
    (check (handler-case (progn (tb:dispose (tb:from-pretrained ".build/fixtures/gpt2/invalid-buffer/")) nil)
             (tb:compatibility-error (c) (search "causal" (princ-to-string c))))
           "modified legacy causal buffers must be rejected"))
  (format t "GPT-2 native acceptance tests passed.~%"))
