;; Pure Lisp contract tests: no model, Python, or native device is needed.
(require :asdf)
(load "examples/query-teacher/domain.lisp")
(in-package #:tb-query-teacher)

(let ((checks 0))
  (flet ((check (value) (incf checks) (assert value)))
    (let ((queries (all-queries)))
      (check (= 36 (length queries)))
      (dolist (query queries)
        (check (equalp query (parse-query (render-query query)))))
      (dolist (bad '("(delete-all)" "#.(error \"read evaluation\")"
                     "(issues :open :tokenizer :week) (delete-all)"
                     "(issues :open :tokenizer :year)" ""))
        (check (null (parse-query bad))))
      (check (equal '(1) (execute-query (parse-query "(issues :open :tokenizer :week)")
                                       (example-issues))))
      (check (equal '(1 2 3 4 5 6) (execute-query (parse-query "(issues :any :any :any)")
                                               (example-issues))))
      (check (equal '(2 4) (execute-query (parse-query "(issues :closed :any :month)")
                                        (example-issues)))))
    (let* ((data (make-curriculum))
           (train (remove-if-not (lambda (x) (eq :train (sample-split x))) data))
           (validation (remove-if-not (lambda (x) (eq :validation (sample-split x))) data))
           (test (remove-if-not (lambda (x) (eq :test (sample-split x))) data))
           (targets (mapcar (lambda (x) (render-query (sample-query x))) train)))
      (check (= 180 (length train)))
      (check (= 30 (length validation)))
      (check (= 36 (length test)))
      (check (= 6 (count-if #'sample-held-combination-p test)))
      (check (= (length data) (length (remove-duplicates data :test #'equal
                                                       :key #'sample-request))))
      (check (equalp data (make-curriculum)))
      (dolist (sample test)
        (check (eq (not (null (member (render-query (sample-query sample)) targets
                                      :test #'equal)))
                   (not (sample-held-combination-p sample)))))
      (dolist (sample data)
        (check (parse-query (render-query (sample-query sample)))))))
  (format t "~&Query teacher: ~D checks passed.~%" checks))
