(in-package #:tb-tests)

(defun run-qwen2-tests ()
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (real (uiop:getenv "TB_QWEN2_REAL"))
         (folder (merge-pathnames (if real ".build/models/qwen2.5-0.5b/"
                                      ".build/fixtures/qwen2/") root))
         (reference (tb::read-json (merge-pathnames "reference.json" folder)))
         (ids (json-array (gethash "input_ids" reference)))
         (mask (json-array (gethash "attention_mask" reference)))
         (labels (and (not real) (json-array (gethash "labels" reference))))
         (expected (json-array (gethash "logits" reference)))
         (vocabulary (array-dimension expected 2))
         (atol (if real 1e-3 3e-5)))
    (let ((capabilities (tb:inspect-pretrained folder)))
      (check (eq (getf capabilities :architecture) :qwen2)
             "Qwen2 architecture is discoverable")
      (check (every (lambda (operation) (member operation (getf capabilities :operations)))
                    '(:forward :training :training-checkpoint :cache :generation :lora :rslora))
             "Qwen2 native operations are discoverable"))
    (tb:with-resource (model (tb:from-pretrained folder :device device))
      (check (typep model 'tb::qwen2-model) "Qwen2 architecture dispatch")
      (check (= (if real 290 27) (length (tb:named-parameters model)))
             "Qwen2 canonical parameter coverage")
      (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
        (format t "~&Qwen2 ~A max error: ~E~%" device
                (close-arrays (tb:tensor-array logits) expected atol 3e-4)))
      (tb:with-resource (cache (tb:make-cache model))
        (dotimes (position 4)
          (let ((step (make-array '(2 1)))
                (padding (make-array (list 2 (1+ position)))))
            (dotimes (batch 2)
              (setf (aref step batch 0) (aref ids batch position))
              (dotimes (i (1+ position))
                (setf (aref padding batch i) (aref mask batch i))))
            (tb:with-resource (logits (tb:forward model step :cache cache :attention-mask padding))
              (let* ((actual (tb:tensor-array logits))
                     (slice (make-array (array-dimensions actual))))
                (dotimes (batch 2)
                  (dotimes (token vocabulary)
                    (setf (aref slice batch 0 token)
                          (aref expected batch position token))))
                (close-arrays actual slice atol 3e-4)))))
      (check (equalp (tb:generate model #(3 4) :max-new-tokens 4 :eos-token-id nil)
                     (gethash "generated" reference))
             "Qwen2 greedy generation")
      (let* ((tokenizer (tb::read-json (merge-pathnames "tokenizer-reference.json" folder)))
             (encoded (tb:encode-text model (gethash "text" tokenizer)
                                      :add-special-tokens nil)))
        (check (equalp encoded (gethash "ids" tokenizer)) "Qwen2 tokenizer IDs")
        (check (equal (tb:decode-tokens model encoded) (gethash "decoded" tokenizer))
               "Qwen2 tokenizer decode"))
      (unless real
        (multiple-value-bind (loss gradients)
            (tb:loss-and-gradients model ids :labels labels :attention-mask mask)
          (let ((expected-gradients (make-hash-table :test 'equal)))
            (unwind-protect
                 (progn
                   (tb::load-weights (merge-pathnames "gradients.safetensors" folder)
                                     (tb:model-backend model) expected-gradients)
                   (check (< (abs (- loss (gethash "loss" reference))) 2e-5)
                          "Qwen2 masked loss")
                   (check (= (length gradients) (hash-table-count expected-gradients))
                          "Qwen2 gradient coverage")
                   (dolist (entry gradients)
                     (close-arrays (tb:tensor-array (cdr entry))
                                   (tb:tensor-array (gethash (car entry) expected-gradients))
                                   4e-6 4e-4)))
              (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)
              (maphash (lambda (name value) (declare (ignore name)) (tb:dispose value))
                       expected-gradients)))))
      (dolist (entry '(("use_sliding_window" . yason:true)
                       ("use_mrope" . yason:true)
                       ("attention_dropout" . 0.1)
                       ("new_attention_scheme" . yason:true)))
        (let ((config (alexandria:copy-hash-table (tb:model-config model))))
          (setf (gethash (car entry) config) (cdr entry))
          (signals tb:compatibility-error (tb::validate-config config))))
      (let ((config (alexandria:copy-hash-table (tb:model-config model))))
        (setf (gethash "layer_types" config) #("full_attention" "sliding_attention"))
        (signals tb:compatibility-error (tb::validate-config config)))
      ;; Qwen2.5 Hub configs from Transformers 4 retain an inactive window size,
      ;; use rope_theta directly, and include use_mrope=false.
      (let ((config (alexandria:copy-hash-table (tb:model-config model))))
        (remhash "layer_types" config)
        (remhash "rope_parameters" config)
        (setf (gethash "rope_theta" config) 1000000.0
              (gethash "sliding_window" config) 32768
              (gethash "use_mrope" config) 'yason:false)
        (check (eq config (tb::validate-config config))
               "official inactive Qwen2.5 options remain loadable"))
      (let ((destination
              (merge-pathnames
               (format nil ".build/qwen2-export-~:[~;real-~]~(~A~)/" real device) root)))
        (tb:save-pretrained model destination)
        (tb:with-resource (reloaded (tb:from-pretrained destination :device device))
          (tb:with-resource (logits (tb:forward reloaded ids :attention-mask mask))
            (close-arrays (tb:tensor-array logits) expected atol 3e-4))))
      (unless real
        (tb:sgd-step model ids :labels labels :attention-mask mask :learning-rate 0.01)
        (tb:save-pretrained model
                            (merge-pathnames (format nil ".build/qwen2-updated-~(~A~)/" device) root)))))
  (unless (uiop:getenv "TB_QWEN2_REAL")
    (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
           (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
           (folder (merge-pathnames ".build/fixtures/qwen2/" root))
           (reference (tb::read-json (merge-pathnames "adapter/reference.json" folder)))
           (expected (json-array (gethash "logits" reference)))
           (ids #2A((3 4 5 6) (7 5 4 3)))
           (mask #2A((1 1 1 0) (1 1 1 1))))
      (tb:with-resource (model (tb:from-pretrained folder :device device))
        (tb:load-adapter model (merge-pathnames "adapter/" folder))
        (check (= 8 (length (tb:trainable-parameters model)))
               "Qwen2 adapter exposes only LoRA parameters")
        (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
          (close-arrays (tb:tensor-array logits) expected 3e-5 3e-4))
        (tb:save-adapter
         model (merge-pathnames (format nil ".build/qwen2-adapter-~(~A~)/" device) root))
        (tb:merge-adapter model)
        (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
          (close-arrays (tb:tensor-array logits) expected 3e-5 3e-4))
        (tb:save-pretrained
         model (merge-pathnames (format nil ".build/qwen2-merged-~(~A~)/" device) root)))))
  (format t "Qwen2 native acceptance tests passed.~%")))
