(in-package #:tb-tests)

(defclass unqualified-composed (tb:composed-causal-lm) ())

(defun recomposition-cases (root device real)
  (let ((output (merge-pathnames (format nil ".build/recomposition-~(~A~)/" device) root))
        (source (merge-pathnames (format nil ".build/components-created-~(~A~)/" device) root)))
    (if real
        (list (list (merge-pathnames (format nil ".build/composition-import-~(~A~)/real/" device) root)
                    (merge-pathnames "real/" output) (coerce (loop for i below 30 by 2 collect i) 'vector)))
        (loop for kind in '("untied" "tied") append
          (loop for (name . indices) in '(("identity" . #(0 1)) ("drop" . #(1))
                                         ("reverse" . #(1 0)) ("repeat" . #(1 0 1)))
                collect (list (if (equal kind "tied") (merge-pathnames "tied/" source) source)
                              (merge-pathnames (format nil "~A/~A/" kind name) output) indices))))))

(defun recomposition-reference (target)
  (tb::read-json (merge-pathnames (format nil "~A-reference.json" (car (last (pathname-directory target))))
                                  (uiop:pathname-parent-directory-pathname target))))

(defun check-recomposition-rejections (model target)
  (dolist (indices (list nil #() "01" '(0 . 1) #(-1) #(2) #(0.0) #(0 "1")))
    (signals tb:compatibility-error (tb:save-recomposed-pretrained model target indices)))
  (let ((circular (list 0)))
    (setf (cdr circular) circular)
    (signals tb:compatibility-error (tb:save-recomposed-pretrained model target circular)))
  (signals tb:compatibility-error (tb:save-recomposed-pretrained nil target #(0)))
  (signals tb:shape-error (tb:save-recomposed-pretrained model target #(0) :max-shard-size 0))
  (signals tb:compatibility-error (tb:save-recomposed-pretrained model (tb::model-directory model) #(0)))
  (unwind-protect
       (progn (change-class model 'unqualified-composed)
              (signals tb:compatibility-error (tb:save-recomposed-pretrained model target #(0))))
    (change-class model 'tb:composed-causal-lm))
  (let* ((description (aref (gethash "block_configs" (tb:model-config model)) 0))
         (epsilon (gethash "rms_norm_eps" description)))
    (unwind-protect
         (progn (setf (gethash "rms_norm_eps" description) 0.1)
                (signals tb:compatibility-error (tb:save-recomposed-pretrained model target #(0))))
      (setf (gethash "rms_norm_eps" description) epsilon)))
  (let* ((table (tb::parameters model)) (name "model.layers.0.self_attn.q_proj.weight")
         (weight (gethash name table)))
    (unwind-protect
         (progn (remhash name table)
                (signals tb:compatibility-error (tb:save-recomposed-pretrained model target #(1))))
      (setf (gethash name table) weight)))
  (tb:make-lora model :rank 2 :alpha 4)
  (signals tb:compatibility-error (tb:save-recomposed-pretrained model target #(0)))
  (tb:remove-adapter model))

(defun recomposition-check-training (model target ids mask labels reference device)
  (multiple-value-bind (loss gradients) (tb:loss-and-gradients model ids :attention-mask mask :labels labels)
    (unwind-protect
         (progn
           (check (< (abs (- loss (gethash "loss" reference))) 2e-6) "recomposed masked loss matches Python")
           (check (= (length gradients) (length (tb:named-parameters model))) "every selected parameter is differentiated")
           (tb::save-weights gradients (merge-pathnames "native-gradients.safetensors" target)))
      (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)))
  (tb:sgd-step model ids :attention-mask mask :labels labels :learning-rate 0.01)
  (tb:save-pretrained model (merge-pathnames "updated/" target))
  (let ((checkpoint (merge-pathnames "resume/" target)))
    (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001))
      (tb:train-step model optimizer ids :attention-mask mask :labels labels)
      (tb:save-training-checkpoint model optimizer checkpoint)
      (tb:with-resource (restored (tb:from-pretrained checkpoint :device device))
        (tb:with-resource (next (tb:make-adamw :learning-rate 0.001))
          (check (= 1 (tb:restore-training-checkpoint restored next checkpoint)) "recomposed optimizer restores its step")
          (check (= (tb:train-step model optimizer ids :attention-mask mask :labels labels)
                     (tb:train-step restored next ids :attention-mask mask :labels labels)) "recomposed resume loss is exact")
          (loop for first in (tb:named-parameters model) for second in (tb:named-parameters restored) do
            (check (equal (car first) (car second)) "resumed parameter names agree")
            (close-arrays (tb:tensor-array (cdr first)) (tb:tensor-array (cdr second)) 0 0)))))))

(defun recomposition-check-adapter (model target ids mask labels)
  (tb:make-lora model :rank 2 :alpha 4 :seed 37)
  (check (= (* 4 (length (tb:transformer-blocks model))) (length (tb:trainable-parameters model)))
         "all selected query/value projections have independent adapters")
  (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001))
    (tb:train-step model optimizer ids :attention-mask mask :labels labels :max-grad-norm 1.0))
  (tb:save-adapter model (merge-pathnames "adapter/" target))
  (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
    (tb::save-weights (list (cons "logits" logits)) (merge-pathnames "adapter-logits.safetensors" target)))
  (tb:remove-adapter model))

(defun run-recomposition-tests ()
  (tb::ensure-native)
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (real (equal (uiop:getenv "TB_RECOMPOSITION_REAL") "1"))
         (root (asdf:system-source-directory "cl-transformer-blocks"))
         (handles (tb::%tb-live-tensors)))
    (loop for (base target indices) in (recomposition-cases root device real) do
      (let* ((reference (recomposition-reference target))
             (ids (json-array (gethash "input_ids" reference)))
             (mask (json-array (gethash "attention_mask" reference)))
             (labels (json-array (gethash "labels" reference))))
        (tb:with-resource (source (tb:from-pretrained base :device device))
          (unless real (check-recomposition-rejections source target))
          (let ((config (tb::copy-component-data (tb:model-config source))))
            (tb:with-resource (before (tb:forward source ids :attention-mask mask))
              (tb:save-recomposed-pretrained source target (coerce indices 'list) :max-shard-size (if real 16777216 1024))
              (tb:with-resource (after (tb:forward source ids :attention-mask mask))
                (close-arrays (tb:tensor-array after) (tb:tensor-array before) 0 0)))
            (check (tb::same-component-data-p config (tb:model-config source)) "selection leaves source architecture unchanged"))
          (when (and (not real) (= (length indices) 1))
            (let ((sentinel (merge-pathnames "previous-export" target)))
              (with-open-file (stream sentinel :direction :output :if-exists :supersede) (write-string "old output" stream))
              (let ((tb::*before-directory-publication*
                      (lambda (stage published) (declare (ignore stage published)) (error "injected layer-reuse failure"))))
                (signals error (tb:save-recomposed-pretrained source target #(0))))
              (check (equal (uiop:read-file-string sentinel) "old output") "failed layer reuse preserves the complete prior output")
              (tb:save-recomposed-pretrained source target indices :max-shard-size 1024)
              (check (not (probe-file sentinel)) "successful layer reuse replaces old output"))))
        ;; Reload after source disposal. Repeated indices no longer share parameter ownership.
        (tb:with-resource (model (tb:from-pretrained target :device device))
          (check (= (length indices) (length (tb:transformer-blocks model))) "selected block count")
          (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
            (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference)) (if real 1e-3 2e-6) 3e-4)
            (tb::save-weights (list (cons "logits" logits)) (merge-pathnames "native-logits.safetensors" target)))
          (tb::write-json (tb:generate model #(3 4) :max-new-tokens 4 :eos-token-id nil)
                          (merge-pathnames "native-generation.json" target))
          (recomposition-check-adapter model target ids mask labels)
          (if real
              (progn
                (tb:attach-tokenizer model target)
                (check (plusp (length (tb:encode-text model "Common Lisp is fast and fun"))) "selected real model tokenizes text")
                (tb:save-pretrained model (merge-pathnames "resaved/" target) :max-shard-size 16777216))
              (recomposition-check-training model target ids mask labels reference device)))))
    (check (= handles (tb::%tb-live-tensors)) "recomposed models/adapters/optimizers release native handles")
    (format t "~&Recomposed native gates passed: ~A, real=~S (~D checks).~%" device real *checks*)))

(defun run-recomposition-roundtrip-tests ()
  (let* ((device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (root (asdf:system-source-directory "cl-transformer-blocks")))
    (loop for entry in (recomposition-cases root device nil) for target = (second entry) do
      (let* ((inputs (recomposition-reference target))
             (directory (merge-pathnames "python-continued/" target))
             (reference (tb::read-json (merge-pathnames "reference.json" directory))))
        (tb:with-resource (model (tb:from-pretrained directory :device device))
          (tb:with-resource (logits (tb:forward model (json-array (gethash "input_ids" inputs))
                                           :attention-mask (json-array (gethash "attention_mask" inputs))))
            (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" reference)) 2e-6 3e-4))
          (multiple-value-bind (loss gradients)
              (tb:loss-and-gradients model (json-array (gethash "input_ids" inputs))
                                     :attention-mask (json-array (gethash "attention_mask" inputs))
                                     :labels (json-array (gethash "labels" inputs)))
            (unwind-protect
                 (progn
                   (check (< (abs (- loss (gethash "loss" reference))) 2e-6) "Python-trained stack returns matching loss to Lisp")
                   (check (= (length gradients) (length (tb:named-parameters model))) "returned stack remains fully trainable"))
              (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients))))))
    (format t "~&Python-trained recomposed models reload in Lisp: ~A (~D checks).~%" device *checks*)))
