(defpackage #:tb-tests (:use #:cl))
(in-package #:tb-tests)
(defvar *checks* 0)
(defun check (value &optional (message "check failed"))
  (incf *checks*) (unless value (error "~A" message)))
(defun close-arrays (a b &optional (atol 2e-5) (rtol 2e-4))
  (check (equal (array-dimensions a) (array-dimensions b)) "shape mismatch")
  (let ((maximum 0.0))
    (dotimes (i (array-total-size a))
      (let* ((x (row-major-aref a i)) (y (row-major-aref b i)) (delta (abs (- x y))))
        (setf maximum (max maximum delta))
        (check (<= delta (+ atol (* rtol (abs y))))
               (format nil "numeric mismatch at ~D: ~A vs ~A" i x y))))
    maximum))
(defun json-array (value)
  (let* ((shape (loop for x = value then (aref x 0)
                      while (and (vectorp x) (not (stringp x))) collect (length x)))
         (out (make-array shape)) (index 0))
    (labels ((walk (x) (if (and (vectorp x) (not (stringp x)))
                          (map nil #'walk x)
                          (setf (row-major-aref out (prog1 index (incf index))) x))))
      (walk value)) out))
(defmacro signals (type &body body)
  `(check (handler-case (progn ,@body nil) (,type () t)) ,(format nil "expected ~S" type)))
(defun run-tests ()
  (setf *checks* 0)
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (fixture (merge-pathnames (or (uiop:getenv "TB_FIXTURE") ".build/fixtures/tiny/") root))
         (output-prefix (or (uiop:getenv "TB_OUTPUT_PREFIX") ""))
         (device (let ((value (or (uiop:getenv "TB_DEVICE") "cpu")))
                   (cond ((equal value "gpu") :gpu) ((equal value "cpu") :cpu)
                         (t (error "TB_DEVICE must be cpu or gpu")))))
         (ref (tb::read-json (merge-pathnames "reference.json" fixture)))
         (ids (json-array (gethash "input_ids" ref)))
         (expected (json-array (gethash "logits" ref)))
         ;; Calibrated against an independent float64 Torch run; see docs/validation.md.
         (logit-atol (if (= 32 (array-dimension expected 2)) 2e-5 1e-3)))
    (let ((capabilities (tb:inspect-pretrained fixture)))
      (check (getf capabilities :supported-p) "Llama config is natively supported")
      (check (eq (getf capabilities :execution) :native) "inspection reports native execution")
      (check (equal (getf capabilities :model-type) "llama") "inspection reports model type")
      (check (eq (getf capabilities :architecture) :llama) "inspection reports architecture")
      (check (equal (getf capabilities :supported-devices) '(:cpu :gpu))
             "native device kinds are explicit")
      (check (every (lambda (operation) (member operation (getf capabilities :operations)))
                    '(:forward :training :training-checkpoint :export :tokenization
                      :cache :generation :lora))
             "Llama operations are discoverable")
      (check (eq (getf capabilities :execution-dtype) :float32)
             "native precision policy is discoverable")
      (check (getf capabilities :python-fallback-p) "Python fallback is explicit"))
    (let* ((unsupported (merge-pathnames ".build/unsupported-capability/" root))
           (config (make-hash-table :test 'equal)))
      (ensure-directories-exist unsupported)
      (setf (gethash "model_type" config) "opt")
      (tb::write-json config (merge-pathnames "config.json" unsupported))
      (let ((capabilities (tb:inspect-pretrained unsupported)))
        (check (not (getf capabilities :supported-p)) "unknown native model is reported")
        (check (equal (getf capabilities :model-type) "opt") "unknown model type is preserved")
        (check (search "Unregistered" (getf capabilities :reason))
               "unsupported report explains native rejection")
        (check (getf capabilities :python-fallback-p) "unsupported native model offers Python")))
    (let* ((unsupported (merge-pathnames ".build/incompatible-capability/" root))
           (config (alexandria:copy-hash-table (tb::read-json
                                                (merge-pathnames "config.json" fixture)))))
      (ensure-directories-exist unsupported)
      (setf (gethash "hidden_act" config) "gelu")
      (tb::write-json config (merge-pathnames "config.json" unsupported))
      (let ((capabilities (tb:inspect-pretrained unsupported)))
        (check (not (getf capabilities :supported-p))
               "recognized model with unsupported semantics is reported")
        (check (equal (getf capabilities :model-type) "llama")
               "incompatible report retains the model family")
        (check (eq (getf capabilities :architecture) :llama)
               "incompatible report retains the registered architecture")
        (check (search "SiLU" (getf capabilities :reason))
               "incompatible report identifies the unsupported semantics")))
    (tb:with-resource (backend (tb:make-backend :device device))
      (tb:with-resource (a (tb:tensor-from-array backend #2A((1 2) (3 4))))
        (check (eq (tb:tensor-dtype a) :float32) "native float dtype")
        (let ((tb::*backend* backend))
          (tb:with-resource (b (tb::matmul a a))
            (close-arrays (tb:tensor-array b) #2A((7 10) (15 22)) 0 0))
          (tb:with-resource (transposed (tb::permute a '(1 0)))
            (close-arrays (tb:tensor-array transposed) #2A((1 3) (2 4)) 0 0))
          (tb:with-resource (retained (tb::retain-tensor a))
            (tb:dispose a) (tb:dispose a)
            (close-arrays (tb:tensor-array retained) #2A((1 2) (3 4)) 0 0)
            (signals tb:backend-error (tb:tensor-array a)))))
      (tb:with-resource (indices (tb:tensor-from-array backend #(1 2 3) :dtype :int32))
        (check (eq (tb:tensor-dtype indices) :int32) "native integer dtype")))
    (tb:with-resource (model (tb:from-pretrained fixture :device device))
      (signals tb:compatibility-error
        (tb:forward model ids :token-type-ids (make-array (array-dimensions ids) :initial-element 0)))
      (signals tb:compatibility-error
        (tb:loss-and-gradients model ids
          :token-type-ids (make-array (array-dimensions ids) :initial-element 0)))
      (let ((before (tb:backend-memory (tb:model-backend model))))
        (check (every (lambda (key) (typep (getf before key) '(integer 0)))
                      '(:active :cache :peak :handles))
               "backend memory report contains nonnegative counters")
        (tb:reset-backend-peak-memory (tb:model-backend model))
        (let ((after (tb:backend-memory (tb:model-backend model))))
          (check (>= (getf after :peak) (getf after :active))
                 "reset peak remains at least active allocation")))
      (let ((capabilities (tb:model-capabilities model)))
        (check (getf capabilities :loaded-p) "loaded native capability state")
        (check (eq (getf capabilities :device) device) "loaded native device")
        (check (if (eq device :cpu)
                   (null (getf capabilities :device-api))
                   (member (getf capabilities :device-api) '(:metal :cuda)))
               "loaded native report distinguishes the GPU API")
        (check (= (getf capabilities :parameter-count)
                  (length (tb:named-parameters model))) "loaded native parameter count"))
      (tb:with-resource (logits (tb:forward model ids))
        (when (> (array-dimension expected 2) 32)
          (tb::save-weights (list (cons "logits" logits))
                           (merge-pathnames (format nil ".build/real-logits-~(~A~).safetensors" device) root)))
        (format t "~&~A logits max error: ~E~%" device
                (close-arrays (tb:tensor-array logits) expected logit-atol)))
      (signals tb:shape-error (tb:forward model #2A((-1 2))))
      (signals tb:shape-error (tb:forward model #(3 4)))
      ;; Prefix attention cannot see future tokens; cached decoding must match full forward.
      (tb:with-resource (cache (tb:make-cache model))
        (dotimes (position 4)
          (let ((step (make-array '(2 1))))
            (dotimes (batch 2) (setf (aref step batch 0) (aref ids batch position)))
            (tb:with-resource (logits (tb:forward model step :cache cache))
              (let* ((actual (tb:tensor-array logits))
                     (slice (make-array (array-dimensions actual))))
                (dotimes (b 2) (dotimes (v (array-dimension expected 2))
                  (setf (aref slice b 0 v) (aref expected b position v))))
                (close-arrays actual slice logit-atol))))))
      ;; Cache storage grows in bounded blocks instead of reallocating every token.
      (signals tb:shape-error (tb:make-cache model :growth-step 0))
      (tb:with-resource (cache (tb:make-cache model :growth-step 3))
        (check (= 0 (tb:cache-length cache)) "new cache has no committed tokens")
        (check (= 0 (tb:cache-capacity cache)) "new cache has no allocated token slots")
        (tb:with-resource (logits (tb:forward model #2A((3 4)) :cache cache))
          (check (= 2 (second (tb:tensor-shape logits))) "block-cache prefill logits"))
        (check (= 2 (tb:cache-length cache)) "prefill advances cache length")
        (check (= 3 (tb:cache-capacity cache)) "prefill reserves one cache block")
        (tb:with-resource (logits (tb:forward model #2A((5)) :cache cache))
          (check (= 1 (second (tb:tensor-shape logits))) "block-cache token logits"))
        (check (= 3 (tb:cache-capacity cache)) "decode reuses reserved cache storage")
        (tb:with-resource (logits (tb:forward model #2A((6 7)) :cache cache))
          (check (= 2 (second (tb:tensor-shape logits))) "block-cache chunk logits"))
        (check (= 5 (tb:cache-length cache)) "chunked decode advances cache length")
        (check (= 6 (tb:cache-capacity cache)) "cache adds only the required block")
        (loop for entry across (tb::cache-entries cache) do
          (check (= 6 (third (tb:tensor-shape (first entry))))
                 "key storage retains reserved capacity")
          (check (= 6 (third (tb:tensor-shape (second entry))))
                 "value storage retains reserved capacity")))
      (let* ((ref (tb::read-json (merge-pathnames "tokenizer-reference.json" fixture)))
             (encoded (tb:encode-text model (gethash "text" ref) :add-special-tokens nil)))
        (check (equalp encoded (gethash "ids" ref)) "native tokenizer encoding")
        (check (equal (tb:decode-tokens model encoded) (gethash "decoded" ref)) "native tokenizer decoding"))
      (let ((generated (tb:generate model #(3 4) :max-new-tokens 4 :eos-token-id nil))
            (expected (tb::read-json (merge-pathnames "generation-reference.json" fixture))))
        (check (equalp generated expected) "greedy generation must match Python")
        (check (= 3 (length (tb:generate model #(3 4) :max-new-tokens 4 :eos-token-id (aref expected 2))))
               "stop immediately after generated EOS"))
      ;; Right padding must be isolated, including full-vs-chunked cache evaluation.
      (tb:with-resource (padded (tb:forward model ids :attention-mask #2A((1 1 0 0) (1 1 1 1))))
        (let ((p (tb:tensor-array padded)))
          (dotimes (b 2) (dotimes (time (if (= b 0) 2 4))
            (dotimes (v (array-dimension p 2))
              (check (< (abs (- (aref p b time v) (aref expected b time v))) logit-atol)
                     "padding changed a valid token"))))))
      (signals tb:compatibility-error (tb:forward model ids :attention-mask #2A((0 1 1 1) (1 1 1 1))))
      (signals tb:shape-error (tb:forward model ids :attention-mask #2A((0 0 0 0) (1 1 1 1))))
      (tb:with-resource (cache (tb:make-cache model))
        (tb:with-resource (prefix (tb:forward model #2A((3 4) (7 5)) :cache cache))
          (check (equal (tb:tensor-shape prefix) (list 2 2 (array-dimension expected 2)))))
        (tb:with-resource (tail (tb:forward model #2A((5 6) (4 3)) :cache cache))
          (let* ((actual (tb:tensor-array tail)) (slice (make-array (array-dimensions actual))))
            (dotimes (b 2) (dotimes (time 2) (dotimes (v (array-dimension slice 2))
              (setf (aref slice b time v) (aref expected b (+ 2 time) v)))))
            (close-arrays actual slice logit-atol))))
      ;; Validate before opening weights or allocating a device.
      (let ((invalid (merge-pathnames ".build/invalid-config/" root)))
        (ensure-directories-exist invalid)
        (dolist (entry '(("model_type" . "unknown") ("hidden_act" . "gelu")
                         ("rope_interleaved" . yason:true) ("new_attention_scheme" . yason:true)))
          (let ((c (alexandria:copy-hash-table (tb:model-config model))))
            (setf (gethash (car entry) c) (cdr entry))
            (tb::write-json c (merge-pathnames "config.json" invalid))
            (signals tb:compatibility-error (tb::validate-config c)))))
      (let ((exported (tb:save-pretrained model (merge-pathnames (format nil ".build/~Aexport-~(~A~)/" output-prefix device) root))))
        (tb:with-resource (reloaded (tb:from-pretrained exported :device device))
          (tb:with-resource (logits (tb:forward reloaded ids))
            (close-arrays (tb:tensor-array logits) expected logit-atol))))
      ;; A failed staged export must leave the previously published directory intact.
      (let* ((destination
               (merge-pathnames (format nil ".build/~Atransactional-export-~(~A~)/"
                                        output-prefix device)
                                root))
             (sentinel (merge-pathnames "previous-checkpoint" destination)))
        (uiop:delete-directory-tree destination :validate t :if-does-not-exist :ignore)
        (ensure-directories-exist sentinel)
        (with-open-file (stream sentinel :direction :output :if-exists :supersede)
          (write-string "still complete" stream))
        (let ((tb::*before-directory-publication*
                (lambda (staging published)
                  (declare (ignore staging published))
                  (error "injected publication failure"))))
          (signals error (tb:save-pretrained model destination)))
        (check (equal (uiop:read-file-string sentinel) "still complete")
               "failed publication preserves the previous checkpoint")
        (check (not (probe-file (merge-pathnames "config.json" destination)))
               "failed publication exposes none of the staged checkpoint")
        (tb:save-pretrained model destination)
        (check (not (probe-file sentinel))
               "successful publication replaces the complete old directory")
        (check (probe-file (merge-pathnames "model.safetensors" destination))
               "successful publication exposes standard model weights")
        (check (probe-file (merge-pathnames "config.json" destination))
               "successful publication exposes its matching configuration")
        (check (null (remove-if-not
                      (lambda (path) (search "/.tb-stage-" (namestring path)))
                      (uiop:subdirectories
                       (uiop:pathname-parent-directory-pathname destination))))
               "publication leaves no staging directory"))
      (let ((sharded (merge-pathnames
                      (format nil ".build/~Asharded-export-~(~A~)/" output-prefix device)
                      root)))
        (uiop:delete-directory-tree sharded :validate t :if-does-not-exist :ignore)
        (signals tb:shape-error (tb:save-pretrained model sharded :max-shard-size 0))
        (let ((stale (merge-pathnames "model-99999-of-99999.safetensors" sharded)))
          (ensure-directories-exist stale)
          (with-open-file (stream stale :direction :output :if-exists :supersede)
            (write-string "stale" stream)))
        (tb:save-pretrained model sharded :max-shard-size 2048)
        (check (not (probe-file (merge-pathnames "model-99999-of-99999.safetensors"
                                                 sharded)))
               "replacement export removes stale model shards")
        (check (not (probe-file (merge-pathnames "model.safetensors" sharded)))
               "multi-shard export omits the unsharded weight file")
        (let* ((index (tb::read-json
                       (merge-pathnames "model.safetensors.index.json" sharded)))
               (weight-map (gethash "weight_map" index))
               (metadata (gethash "metadata" index))
               (files (remove-duplicates
                       (loop for file being the hash-values of weight-map collect file)
                       :test #'equal))
               (parameters (tb:named-parameters model))
               (total-bytes
                 (loop for entry in parameters
                       sum (* 4 (reduce #'* (tb:tensor-shape (cdr entry)))))))
          (check (> (length files) 1) "small shard limit produces multiple files")
          (check (= (hash-table-count weight-map) (length parameters))
                 "shard index covers every canonical parameter")
          (check (= (gethash "total_size" metadata) total-bytes)
                 "shard index records exact FP32 byte size")
          (dolist (entry parameters)
            (check (probe-file (merge-pathnames (gethash (car entry) weight-map) sharded))
                   "every indexed parameter names an existing shard")))
        (tb:with-resource (reloaded (tb:from-pretrained sharded :device device))
          (tb:with-resource (logits (tb:forward reloaded ids))
            (close-arrays (tb:tensor-array logits) expected logit-atol))))
      (when (= 16 (gethash "hidden_size" (tb:model-config model)))
        (tb:with-resource (untied (tb:from-pretrained (merge-pathnames "untied/" fixture) :device device))
          (check (= 1 (- (length (tb:named-parameters untied)) (length (tb:named-parameters model))))
                 "untied output is a distinct canonical parameter")
          (tb:with-resource (logits (tb:forward untied ids))
            (close-arrays (tb:tensor-array logits) expected))
          (tb:save-pretrained untied (merge-pathnames (format nil ".build/untied-export-~(~A~)/" device) root)))
        (tb:with-resource (sharded (tb:from-pretrained (merge-pathnames "sharded/" fixture) :device device))
          (tb:with-resource (logits (tb:forward sharded ids))
            (close-arrays (tb:tensor-array logits) expected)))
        (dolist (entry '(("missing/" . "Missing tensor") ("extra/" . "Unexpected tensor")
                         ("shape/" . "expected")))
          (check (handler-case
                     (progn (tb:dispose (tb:from-pretrained (merge-pathnames (car entry) fixture) :device device)) nil)
                   (tb:backend-error (condition)
                     (search (cdr entry) (princ-to-string condition))))
                 "malformed checkpoint must report the actual schema violation"))
        (signals tb:shape-error (tb:push-to-hub model "invalid repository name"))
        (let* ((publication (merge-pathnames
                             (format nil ".build/native-publication-~(~A~)/" device) root))
               (result (tb:push-to-hub model "common-lisp/native-test"
                                       :model-card "# Native test"
                                       :dry-run-directory publication)))
          (check (find "model.safetensors" (gethash "files" result) :test #'equal)
                 "native Hub stage contains safe weights")
          (check (find "README.md" (gethash "files" result) :test #'equal)
                 "native Hub stage contains model card"))
        (let* ((payload nil)
               (response (make-hash-table :test 'equal)))
          (setf (gethash "path" response) (namestring (truename fixture))
                (gethash "resolved_revision" response) "abc123")
          (let ((tb::*hub-command-runner*
                  (lambda (command &key input &allow-other-keys)
                    (declare (ignore command))
                    (check (streamp input) "Hub helper input is an explicit stream")
                    (setf payload (yason:parse input :json-booleans-as-symbols t))
                    (with-output-to-string (stream) (yason:encode response stream)))))
            (tb:with-resource
                (downloaded (tb:from-pretrained "common-lisp/native-test"
                                                :revision "abc123" :local-files-only t
                                                :device device))
              (check (equal (tb::model-source-id downloaded) "common-lisp/native-test")
                     "native model records Hub source")
              (check (equal (tb::model-source-revision downloaded) "abc123")
                     "native model records resolved revision")))
          (check (equal (gethash "repo_id" payload) "common-lisp/native-test")
                 "native Hub helper receives repository")
          (check (tb::json-true-p (gethash "local_files_only" payload))
                 "native Hub helper receives offline policy"))
        (multiple-value-bind (loss gradients) (tb::loss-and-gradients model ids)
          (let ((expected-gradients (make-hash-table :test 'equal)))
            (unwind-protect
                 (progn
                   (tb::load-weights (merge-pathnames "reference-gradients.safetensors" fixture)
                                    (tb:model-backend model) expected-gradients)
                   (check (< (abs (- loss (gethash "loss" ref))) 2e-5) "autodiff loss")
                   (dolist (entry gradients)
                     (close-arrays (tb:tensor-array (cdr entry))
                                   (tb:tensor-array (gethash (car entry) expected-gradients)) 2e-6 2e-4)))
              (mapc (lambda (entry) (tb:dispose (cdr entry))) gradients)
              (maphash (lambda (key value) (declare (ignore key)) (tb:dispose value)) expected-gradients))))
        (tb:with-resource (stale (tb:make-cache model))
          (let ((loss (tb:sgd-step model ids :learning-rate 0.01)))
            (check (< (abs (- loss (gethash "loss" ref))) 2e-5) "training loss parity"))
          (signals tb:compatibility-error (tb:forward model #2A((3 4)) :cache stale)))
        (tb:save-pretrained model (merge-pathnames (format nil ".build/~Aupdated-~(~A~)/" output-prefix device) root)))))
  (format t "~&~D checks passed.~%" *checks*) t)
