(in-package #:tb-tests)

(defun parameter-snapshot (model)
  (mapcar (lambda (entry) (cons (car entry) (tb:tensor-array (cdr entry))))
          (tb:trainable-parameters model)))

(defun check-parameter-snapshot (model expected label)
  (let ((actual (tb:trainable-parameters model)))
    (check (= (length actual) (length expected)) label)
    (dolist (entry expected)
      (close-arrays (cdr entry)
                    (tb:tensor-array (cdr (assoc (car entry) actual :test #'equal)))
                    2e-7 2e-6))))
(defun run-training-tests ()
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (base (merge-pathnames ".build/fixtures/tiny/" root)))
    (dolist (variant '("standard" "rslora"))
      (let* ((path (merge-pathnames (format nil ".build/fixtures/peft/~A/" variant) root))
             (ref (tb::read-json (merge-pathnames "reference.json" path)))
             (ids (json-array (gethash "input_ids" ref)))
             (mask (json-array (gethash "attention_mask" ref)))
             (labels (json-array (gethash "labels" ref))))
        (tb:with-resource (model (tb:from-pretrained base :device device))
          (tb::load-adapter model path)
          (signals tb:compatibility-error (tb:save-pretrained model (merge-pathnames ".build/should-not-export/" root)))
          (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
            (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" ref))))
          (multiple-value-bind (loss gradients) (tb::loss-and-gradients model ids :labels labels :attention-mask mask)
            (let ((expected (make-hash-table :test 'equal)))
              (unwind-protect
                   (progn
                     (tb::load-weights (merge-pathnames "gradients.safetensors" path) (tb:model-backend model) expected)
                     (check (< (abs (- loss (gethash "loss" ref))) 2e-5) "PEFT masked loss")
                     (check (= (length gradients) (hash-table-count expected)) "only adapter gradients")
                     (dolist (entry gradients)
                       (close-arrays (tb:tensor-array (cdr entry))
                                     (tb:tensor-array (gethash (car entry) expected)) 2e-6 2e-4)))
                (mapc (lambda (p) (tb:dispose (cdr p))) gradients)
                (maphash (lambda (k v) (declare (ignore k)) (tb:dispose v)) expected))))
          (let* ((exported (merge-pathnames
                            (format nil ".build/peft-~A-~(~A~)/" variant device) root))
                 (sentinel (merge-pathnames "previous-adapter" exported)))
            (when (equal variant "standard")
              (uiop:delete-directory-tree exported :validate t :if-does-not-exist :ignore)
              (ensure-directories-exist sentinel)
              (with-open-file (stream sentinel :direction :output :if-exists :supersede)
                (write-string "native adapter" stream))
              (let ((tb::*before-directory-publication*
                      (lambda (staging published)
                        (declare (ignore staging published))
                        (error "injected native-adapter publication failure"))))
                (signals error (tb:save-adapter model exported)))
              (check (equal (uiop:read-file-string sentinel) "native adapter")
                     "failed native adapter publication preserves its predecessor"))
            (tb::save-adapter model exported)
            (when (equal variant "standard")
              (check (not (probe-file sentinel))
                     "native adapter publication replaces the complete directory")))
          (tb::merge-adapter model)
          (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
            (close-arrays (tb:tensor-array logits) (json-array (gethash "logits" ref)) 3e-5 3e-4))
          (tb:save-pretrained model (merge-pathnames (format nil ".build/peft-merged-~A-~(~A~)/" variant device) root)))
        (dolist (algorithm '(:sgd :adamw))
          (tb:with-resource (model (tb:from-pretrained base :device device))
            (tb::load-adapter model path)
            (tb:with-resource (optimizer (if (eq algorithm :sgd)
                                            (tb::make-sgd :learning-rate 0.01 :momentum 0.9 :weight-decay 0.02)
                                            (tb::make-adamw :learning-rate 0.001 :beta1 0.8 :beta2 0.95 :weight-decay 0.02)))
              (let ((expected (tb::read-json (merge-pathnames (format nil "~(~A~)-losses.json" algorithm) path))))
                (dotimes (i 3)
                  (check (< (abs (- (tb::train-step model optimizer ids :labels labels :attention-mask mask :max-grad-norm 0.05)
                                    (aref expected i))) 3e-5) "optimizer loss trajectory")))
              (tb::save-adapter model (merge-pathnames (format nil ".build/peft-~A-~(~A~)-~(~A~)/" variant algorithm device) root))))))))
  (format t "Training interoperability tests passed.~%"))

(defun run-training-edge-tests ()
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (base (merge-pathnames ".build/fixtures/tiny/" root))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (ids #2A((3 4 5 6 0) (7 5 4 3 8)))
         (mask #2A((1 1 1 1 0) (1 1 1 1 1)))
         (labels #2A((-100 -100 5 6 -100) (-100 5 -100 3 8)))
         (baseline-handles (tb::%tb-live-tensors)))
    (tb:with-resource (model (tb:from-pretrained base :device device))
      (tb:with-resource (before (tb:forward model ids :attention-mask mask))
        (tb:make-lora model :rank 2 :alpha 4 :seed 31)
        (tb:with-resource (after (tb:forward model ids :attention-mask mask))
          (close-arrays (tb:tensor-array before) (tb:tensor-array after) 0 0)))
      (let ((original (mapcar (lambda (entry) (cons (car entry) (tb:tensor-array (cdr entry)))) (tb:named-parameters model))))
        (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001))
          (signals tb:shape-error (tb:train-step model optimizer ids :labels (make-array '(2 5) :initial-element -100)))
          (signals tb:shape-error (tb:train-step model optimizer ids :max-grad-norm 0))
          (dotimes (i 4) (tb:train-step model optimizer ids :labels labels :attention-mask mask))
          (let ((memory (tb::backend-memory (tb:model-backend model))))
            (dotimes (i 20) (tb:train-step model optimizer ids :labels labels :attention-mask mask))
            (let ((after (tb::backend-memory (tb:model-backend model))))
              (check (= (getf memory :handles) (getf after :handles)) "native handles leaked over repeated steps")
              (check (<= (getf after :active) (+ (getf memory :active) 65536)) "active native memory grew after warmup")
              (format t "~&~A repeated-step memory: ~S -> ~S~%" device memory after)))
          (dolist (entry original)
            (close-arrays (cdr entry) (tb:tensor-array (cdr (assoc (car entry) (tb:named-parameters model) :test #'equal))) 0 0))
          (tb:save-adapter model (merge-pathnames (format nil ".build/peft-native-~(~A~)/" device) root))
          (tb:with-resource (logits (tb:forward model ids :attention-mask mask))
            (tb::save-weights (list (cons "logits" logits))
                             (merge-pathnames (format nil ".build/native-adapter-logits-~(~A~).safetensors" device) root)))
          (tb:remove-adapter model)
          (signals tb:compatibility-error (tb:train-step model optimizer ids)))
        (let ((path (merge-pathnames ".build/fixtures/peft/standard/" root)))
          (dolist (entry '(("use_dora" . yason:true) ("lora_dropout" . 0.2)
                           ("base_model_name_or_path" . "wrong/base") ("revision" . "wrong-revision")
                           ("unknown_feature" . yason:true)))
            (let ((c (tb::read-json (merge-pathnames "adapter_config.json" path))))
              (setf (gethash (car entry) c) (cdr entry))
              (signals tb:compatibility-error (tb::validate-adapter model c)))))))
    (tb:with-resource (model (tb:from-pretrained base :device device))
      (let* ((folder (merge-pathnames ".build/fixtures/peft/full/" root))
             (expected-gradients (make-hash-table :test 'equal)))
        (multiple-value-bind (loss gradients) (tb:loss-and-gradients model ids :labels labels :attention-mask mask)
          (unwind-protect
               (progn
                 (tb::load-weights (merge-pathnames "gradients.safetensors" folder) (tb:model-backend model) expected-gradients)
                 (check (< (abs (- loss (gethash "loss" (tb::read-json (merge-pathnames "reference.json" folder))))) 2e-5) "full-model masked loss")
                 (dolist (entry gradients)
                   (close-arrays (tb:tensor-array (cdr entry)) (tb:tensor-array (gethash (car entry) expected-gradients)) 2e-6 2e-4)))
            (mapc (lambda (p) (tb:dispose (cdr p))) gradients)
            (maphash (lambda (k v) (declare (ignore k)) (tb:dispose v)) expected-gradients)))
        (tb:with-resource (optimizer (tb:make-adamw :learning-rate 0.001 :beta1 0.8 :beta2 0.95 :weight-decay 0.02))
          (let ((expected (tb::read-json (merge-pathnames "adamw-losses.json" folder))))
            (dotimes (i 3)
              (check (< (abs (- (tb:train-step model optimizer ids :labels labels :attention-mask mask :max-grad-norm 0.05)
                                (aref expected i))) 3e-5) "full-model AdamW trajectory"))))
        (tb:save-pretrained model (merge-pathnames (format nil ".build/full-adamw-~(~A~)/" device) root))))
    (check (= baseline-handles (tb::%tb-live-tensors)) "model/optimizer disposal leaked native handles"))
  (format t "Training memory and edge cases passed.~%"))

(defun run-native-checkpoint-tests ()
  (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
         (base (merge-pathnames ".build/fixtures/tiny/" root))
         (adapter (merge-pathnames ".build/fixtures/peft/standard/" root))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu))
         (ids #2A((3 4 5 6 0) (7 5 4 3 8)))
         (mask #2A((1 1 1 1 0) (1 1 1 1 1)))
         (labels #2A((-100 -100 5 6 -100) (-100 5 -100 3 8))))
    (dolist (kind '(:full :adapter))
      (let ((checkpoint (merge-pathnames
                         (format nil ".build/native-~(~A~)-checkpoint-~(~A~)/" kind device)
                         root))
            (expected-loss nil) (expected-parameters nil))
        (flet ((make-checkpoint-optimizer (&optional mismatch)
                 (if (eq kind :adapter)
                     (tb:make-sgd :learning-rate (if mismatch 0.02 0.01)
                                  :momentum 0.9 :weight-decay 0.02)
                     (tb:make-adamw :learning-rate (if mismatch 0.002 0.001)
                                    :beta1 0.8 :beta2 0.95 :epsilon 1e-7
                                    :weight-decay 0.02))))
          (tb:with-resource (model (tb:from-pretrained base :device device))
            (when (eq kind :adapter) (tb:load-adapter model adapter))
            (tb:with-resource (optimizer (make-checkpoint-optimizer))
              (dotimes (index 2)
                (tb:train-step model optimizer ids :labels labels :attention-mask mask
                               :max-grad-norm 0.05))
              (let ((sentinel (merge-pathnames "previous-checkpoint" checkpoint)))
                (uiop:delete-directory-tree checkpoint :validate t :if-does-not-exist :ignore)
                (ensure-directories-exist sentinel)
                (with-open-file (stream sentinel :direction :output :if-exists :supersede)
                  (write-string "native training checkpoint" stream))
                (let ((tb::*before-directory-publication*
                        (lambda (staging published)
                          (declare (ignore published))
                          (when (probe-file (merge-pathnames "training_state.json" staging))
                            (error "injected complete-checkpoint publication failure")))))
                  (signals error
                    (tb:save-training-checkpoint model optimizer checkpoint)))
                (check (equal (uiop:read-file-string sentinel)
                              "native training checkpoint")
                       "failed native training publication preserves its predecessor")
                (check (not (probe-file (merge-pathnames "training_state.json" checkpoint)))
                       "failed native training publication exposes no new sidecar"))
              (tb:save-training-checkpoint model optimizer checkpoint)
              (check (not (probe-file (merge-pathnames "previous-checkpoint" checkpoint)))
                     "native training publication replaces the complete directory")
              (setf expected-loss
                    (tb:train-step model optimizer ids :labels labels :attention-mask mask
                                   :max-grad-norm 0.05)
                    expected-parameters (parameter-snapshot model))))
          (tb:with-resource (wrong-source (tb:from-pretrained base :device device))
            (when (eq kind :adapter) (tb:load-adapter wrong-source adapter))
            (tb:with-resource (optimizer (make-checkpoint-optimizer))
              (signals tb:compatibility-error
                (tb:restore-training-checkpoint wrong-source optimizer checkpoint))))
          (tb:with-resource (model (tb:from-pretrained (if (eq kind :full) checkpoint base)
                                                       :device device))
            (when (eq kind :adapter) (tb:load-adapter model checkpoint))
            (tb:with-resource (mismatch (make-checkpoint-optimizer t))
              (signals tb:compatibility-error
                (tb:restore-training-checkpoint model mismatch checkpoint)))
            (tb:with-resource (optimizer (make-checkpoint-optimizer))
              (check (= 2 (tb:restore-training-checkpoint model optimizer checkpoint))
                     "native checkpoint restores completed step")
              (check (< (abs (- expected-loss
                                (tb:train-step model optimizer ids :labels labels
                                               :attention-mask mask :max-grad-norm 0.05)))
                        2e-6)
                     "native checkpoint resumes deterministic loss")
              (check-parameter-snapshot model expected-parameters
                                        "native checkpoint resumes exact parameters")))))))
  (format t "Native full-model and adapter checkpoints passed.~%"))
