(load "scripts/load.lisp")
(asdf:load-system "cl-transformer-blocks/tests")
(load "tests/training.lisp")
(setf *print-length* 5 *print-level* 4)
(tb-tests::run-training-tests)
(tb-tests::run-training-edge-tests)
(tb-tests::run-native-checkpoint-tests)
