(in-package #:tb)
(defclass lora-adapter ()
  ((config :initarg :config :reader adapter-config)
   (parameters :initarg :parameters :accessor adapter-parameters)
   (targets :initarg :targets :reader adapter-targets)
   (scale :initarg :scale :reader adapter-scale)
   (directory :initarg :directory :initform nil :reader adapter-directory)))
(defun sorted-parameters (table)
  (sort (loop for name being the hash-keys of table using (hash-value value)
              collect (cons name value)) #'string< :key #'car))
(defmethod named-parameters ((adapter lora-adapter)) (sorted-parameters (adapter-parameters adapter)))
(defmethod dispose ((adapter lora-adapter))
  (maphash (lambda (k v) (declare (ignore k)) (dispose v)) (adapter-parameters adapter))
  (clrhash (adapter-parameters adapter)))
(defgeneric trainable-parameters (model))
(defmethod trainable-parameters ((model model))
  "Borrowed, sorted parameters: the active adapter only, or all base parameters."
  (named-parameters (or (model-adapter model) model)))
(defmethod trainable-parameters ((model python-model))
  (declare (ignore model))
  (fail 'compatibility-error
        "Direct Python parameter transfer is unavailable; use PYTHON-TRAIN-STEP for training"))
(defun adapter-key (base-name factor)
  (format nil "base_model.model.~A.lora_~A.weight" (subseq base-name 0 (- (length base-name) 7)) factor))
(defun adapter-weight (adapter name)
  (or (and *parameter-overrides* (gethash name *parameter-overrides*))
      (gethash name (adapter-parameters adapter))
      (fail 'compatibility-error "Missing LoRA parameter ~A" name)))
(defmethod project :around ((model model) inputs parameter-name)
  (let* ((base (call-next-method)) (adapter (model-adapter model)))
    (if (and adapter (member parameter-name (adapter-targets adapter) :test #'equal))
        (add base (multiply (scalar (adapter-scale adapter))
                           (linear (linear inputs (adapter-weight adapter (adapter-key parameter-name "A")))
                                   (adapter-weight adapter (adapter-key parameter-name "B"))))) base)))
(defun same-base-p (a b)
  (and (stringp a) (stringp b)
       (or (equal a b)
           (and (probe-file a) (probe-file b) (equal (truename a) (truename b))))))
(defun empty-option-p (value)
  (or (null value) (eq value 'yason:false)
      (and (hash-table-p value) (zerop (hash-table-count value)))
      (and (vectorp value) (zerop (length value)))))
(defgeneric adapter-contract (model))
(defmethod adapter-contract ((model model))
  (declare (ignore model))
  (fail 'compatibility-error "Native LoRA is not registered for this architecture"))
(defmethod adapter-contract ((model llama-model))
  (declare (ignore model))
  (values '("q_proj" "k_proj" "v_proj" "o_proj" "gate_proj" "up_proj" "down_proj")
          '(nil "CAUSAL_LM") "CAUSAL_LM" '("q_proj" "v_proj")))
(defmethod adapter-contract ((model composed-causal-lm))
  (validate-composition-state model)
  (unless (model-directory model)
    (fail 'compatibility-error
          "Save and reload the composed base before attaching LoRA so its PEFT reference identifies reusable weights"))
  (call-next-method))
(defmethod adapter-contract ((model bert-masked-lm))
  (declare (ignore model))
  (values '("query" "value")
          '(nil "FEATURE_EXTRACTION") nil '("query" "value")))
(defgeneric valid-adapter-auto-mapping-p (model mapping))
(defmethod valid-adapter-auto-mapping-p ((model model) mapping)
  (declare (ignore model))
  (empty-option-p mapping))
(defmethod valid-adapter-auto-mapping-p ((model bert-masked-lm) mapping)
  (or (empty-option-p mapping)
      (and (hash-table-p mapping)
           (= (hash-table-count mapping) 2)
           (equal (gethash "base_model_class" mapping) "BertForMaskedLM")
           (equal (gethash "parent_library" mapping)
                  "transformers.models.bert.modeling_bert"))))
(defun validate-adapter (model c)
  (when (or (model-adapter model) (base-updated-p model))
    (fail 'compatibility-error "Remove the active adapter, or save/reload modified base weights first"))
  (multiple-value-bind (supported task-types task-type defaults) (adapter-contract model)
    (declare (ignore task-type defaults))
    (unless (and (equal (gethash "peft_type" c) "LORA")
                 (member (gethash "task_type" c) task-types :test #'equal)
                 (equal (gethash "bias" c "none") "none")
                 (zerop (gethash "lora_dropout" c 0)))
      (fail 'compatibility-error "Only a registered bias-free, zero-dropout LoRA task is supported"))
    (unless (same-base-p (gethash "base_model_name_or_path" c) (model-source-id model))
      (fail 'compatibility-error "Adapter base identity does not match this model"))
    (unless (equal (gethash "revision" c) (model-source-revision model))
      (fail 'compatibility-error "Adapter base revision does not match this model"))
    (maphash
     (lambda (key value)
       (cond ((member key '("peft_type" "task_type" "r" "lora_alpha" "target_modules" "lora_dropout"
                           "bias" "base_model_name_or_path" "revision" "use_rslora" "inference_mode"
                           "init_lora_weights" "peft_version" "megatron_core" "qalora_group_size") :test #'equal))
             ((equal key "auto_mapping")
              (unless (valid-adapter-auto-mapping-p model value)
                (fail 'compatibility-error "Unsupported LoRA auto_mapping")))
             ((member key '("fan_in_fan_out" "use_dora" "lora_bias" "modules_to_save" "rank_pattern"
                            "alpha_pattern" "layers_to_transform" "layers_pattern" "layer_replication"
                            "exclude_modules" "target_parameters" "trainable_token_indices" "use_qalora"
                            "alora_invocation_tokens" "arrow_config" "corda_config"
                            "eva_config" "loftq_config" "lora_ga_config" "megatron_config" "monteclora_config"
                            "use_bdlora" "velora_config" "ensure_weight_tying") :test #'equal)
              (unless (empty-option-p value) (fail 'compatibility-error "Unsupported LoRA option: ~A" key)))
             (t (fail 'compatibility-error "Unrecognized LoRA option: ~A" key)))) c)
    (let ((rank (gethash "r" c)) (alpha (gethash "lora_alpha" c))
          (targets (gethash "target_modules" c)))
      (unless (and (typep rank '(integer 1)) (realp alpha) (> alpha 0)
                   (vectorp targets) (not (stringp targets)) (> (length targets) 0)
                   (every (lambda (target) (member target supported :test #'equal)) targets))
        (fail 'compatibility-error "Expected a positive rank/alpha and supported projection-name list"))
      (let ((matched (loop for (name . value) in (named-parameters model) when
                      (some (lambda (target)
                              (alexandria:ends-with-subseq
                               (concatenate 'string "." target ".weight") name))
                            targets)
                      collect name)))
        (values matched (/ (float alpha 1.0)
                           (if (json-true-p (gethash "use_rslora" c))
                               (sqrt (float rank 1.0)) rank)))))))
(defun install-adapter (model c targets scale weights &optional directory)
  (let ((expected (make-hash-table :test 'equal)) (rank (gethash "r" c)))
    (dolist (name targets)
      (destructuring-bind (out in) (tensor-shape (weight model name))
        (setf (gethash (adapter-key name "A") expected) (list rank in)
              (gethash (adapter-key name "B") expected) (list out rank))))
    (unless (= (hash-table-count weights) (hash-table-count expected))
      (fail 'compatibility-error "LoRA tensor coverage mismatch"))
    (maphash (lambda (name shape)
               (unless (and (gethash name weights) (equal shape (tensor-shape (gethash name weights))))
                 (fail 'shape-error "Missing or misshaped LoRA tensor: ~A" name))) expected)
    (setf (model-adapter model)
          (make-instance 'lora-adapter :config c :parameters weights :targets targets
                         :scale scale :directory directory))
    (incf (model-version model)) model))
(defun load-adapter (model directory)
  "Attach one standard PEFT safetensors LoRA adapter, validating its base and options."
  (unless (typep model 'model)
    (fail 'compatibility-error "Native LoRA requires a native model"))
  (pointer (model-backend model))
  (let* ((directory (uiop:ensure-directory-pathname directory))
         (c (read-json (merge-pathnames "adapter_config.json" directory)))
         (weights (make-hash-table :test 'equal)) (success nil))
    (multiple-value-bind (targets scale) (validate-adapter model c)
      (unwind-protect
           (progn (load-weights (merge-pathnames "adapter_model.safetensors" directory) (model-backend model) weights)
                  (install-adapter model c targets scale weights directory) (setf success t) model)
        (unless success (maphash (lambda (k v) (declare (ignore k)) (dispose v)) weights))))))
(defun make-lora (model &key (rank 8) (alpha 16) (targets nil targets-supplied-p)
                              (rslora nil) (seed 17))
  "Attach a reproducibly initialized native LoRA: uniform A, zero B (identity output).
The integer seed uses a local generator, independent of CL implementation random states."
  (unless (typep model 'model)
    (fail 'compatibility-error "Native LoRA requires a native model"))
  (multiple-value-bind (supported task-types task-type defaults) (adapter-contract model)
    (declare (ignore supported task-types))
    (let ((targets (if targets-supplied-p targets defaults))
          (c (make-hash-table :test 'equal))
          (weights (make-hash-table :test 'equal))
          (success nil))
      (loop for (key . value) in `(("peft_type" . "LORA") ("task_type" . ,task-type) ("bias" . "none")
            ("r" . ,rank) ("lora_alpha" . ,alpha) ("target_modules" . ,(coerce targets 'vector))
            ("lora_dropout" . 0) ("use_rslora" . ,(if rslora 'yason:true 'yason:false))
            ("base_model_name_or_path" . ,(model-source-id model)) ("revision" . ,(model-source-revision model)))
            do (setf (gethash key c) value))
      (unless (typep seed '(unsigned-byte 32)) (fail 'shape-error "Seed must be uint32"))
      (multiple-value-bind (matched scale) (validate-adapter model c)
        (unwind-protect
             (progn
               (dolist (name matched)
                 (destructuring-bind (out in) (tensor-shape (weight model name))
                   (let ((a (make-array (list rank in)))
                         (b (make-array (list out rank) :initial-element 0.0)))
                     (dotimes (i (array-total-size a))
                       (setf seed (mod (+ (* 1664525 seed) 1013904223) (expt 2 32))
                             (row-major-aref a i)
                             (/ (- (* 2.0 (/ seed (expt 2 32))) 1.0)
                                (sqrt (float in 1.0)))))
                     (setf (gethash (adapter-key name "A") weights)
                           (tensor-from-array (model-backend model) a)
                           (gethash (adapter-key name "B") weights)
                           (tensor-from-array (model-backend model) b)))))
               (install-adapter model c matched scale weights)
               (setf success t)
               model)
          (unless success
            (maphash (lambda (key value) (declare (ignore key)) (dispose value)) weights)))))))
(defun native-adapter-export-destination (model directory)
  (let* ((directory (uiop:ensure-directory-pathname directory))
         (source (and (model-adapter model) (adapter-directory (model-adapter model)))))
    (when (and source (uiop:directory-exists-p directory)
               (equal (truename directory) (truename source)))
      (fail 'compatibility-error "Export to a separate directory to preserve the source adapter"))
    directory))
(defun write-native-adapter-directory (model directory)
  (unless (typep model 'model)
    (fail 'compatibility-error "Native LoRA requires a native model"))
  (let ((adapter (model-adapter model)) (directory (uiop:ensure-directory-pathname directory)))
    (unless adapter (fail 'compatibility-error "No active adapter"))
    (save-weights (named-parameters adapter) (merge-pathnames "adapter_model.safetensors" directory))
    (let ((c (alexandria:copy-hash-table (adapter-config adapter))))
      (setf (gethash "inference_mode" c) 'yason:true)
      (write-json c (merge-pathnames "adapter_config.json" directory))) directory))
(defun save-adapter (model directory)
  (unless (typep model 'model)
    (fail 'compatibility-error "Native LoRA requires a native model"))
  (unless (model-adapter model) (fail 'compatibility-error "No active adapter"))
  (let ((directory (native-adapter-export-destination model directory)))
    (call-with-staged-directory-publication
     directory (lambda (staging) (write-native-adapter-directory model staging)))))
(defun remove-adapter (model)
  (unless (typep model 'model)
    (fail 'compatibility-error "Native LoRA requires a native model"))
  (when (model-adapter model)
    (dispose (model-adapter model)) (setf (model-adapter model) nil) (incf (model-version model))) model)
(defun merge-adapter (model)
  "Fold delta = scale * B @ A into the base and remove the adapter. Invalidates caches."
  (unless (typep model 'model)
    (fail 'compatibility-error "Native LoRA requires a native model"))
  (let ((adapter (model-adapter model)) (*backend* (model-backend model)) (updated nil) (committed nil))
    (unless adapter (fail 'compatibility-error "No active adapter"))
    (unwind-protect
         (progn
           (with-tensor-scope
             (dolist (name (adapter-targets adapter))
               (let ((merged (add (weight model name)
                                  (multiply (scalar (adapter-scale adapter))
                                            (matmul (adapter-weight adapter (adapter-key name "B"))
                                                    (adapter-weight adapter (adapter-key name "A")))))))
                 (checked-status (%tb-tensor-eval (pointer merged)))
                 (push (cons name (retain-tensor merged)) updated))))
           (dolist (entry updated)
             (dispose (gethash (car entry) (parameters model)))
             (setf (gethash (car entry) (parameters model)) (cdr entry)))
           (setf committed t (base-updated-p model) t) (remove-adapter model))
      (unless committed (mapc (lambda (entry) (dispose (cdr entry))) updated)))))
