(in-package #:tb)

;; Descriptions own no tensors. The model snapshots their versioned semantics.
(defclass rotary-attention ()
  ((heads :initarg :heads :reader component-heads)
   (kv-heads :initarg :kv-heads :reader component-kv-heads)
   (theta :initarg :theta :reader component-theta)))
(defclass swiglu ()
  ((width :initarg :width :reader component-width)))
(defclass transformer-block ()
  ((attention :initarg :attention :reader block-attention)
   (feed-forward :initarg :feed-forward :reader block-feed-forward)
   (epsilon :initarg :epsilon :reader block-epsilon)
   (residual :initarg :residual :reader block-residual)))
(defclass composed-causal-lm (llama-model)
  ((blocks :reader composed-blocks)
   (construction-config :reader construction-config)))
(register-architecture "tb_composed" 'composed-causal-lm)

(defun component-object (&rest entries)
  (let ((table (make-hash-table :test 'equal)))
    (loop for (key value) on entries by #'cddr do (setf (gethash key table) value)) table))
(defun component-positive (value name &optional integer)
  (unless (if integer (typep value '(integer 1 2147483647))
              (and (realp value) (< 0 value most-positive-single-float)))
    (fail 'compatibility-error "Invalid positive component ~A: ~S" name value)) value)
(defun component-keys (object keys)
  (unless (hash-table-p object) (fail 'compatibility-error "Component must be a JSON object"))
  (maphash (lambda (key value) (declare (ignore value))
             (unless (member key keys :test #'equal)
               (fail 'compatibility-error "Unknown component field ~S" key))) object))

(defun make-rotary-attention (&key heads (kv-heads heads) (rope-theta 10000.0))
  "Describe bias-free causal attention with full-head, unscaled Llama-style RoPE."
  (component-positive heads "head count" t)
  (component-positive kv-heads "KV head count" t)
  (component-positive rope-theta "RoPE base")
  (unless (zerop (mod heads kv-heads))
    (fail 'compatibility-error "Attention heads must be divisible by KV heads"))
  (make-instance 'rotary-attention :heads heads :kv-heads kv-heads :theta rope-theta))
(defun make-swiglu (&key intermediate-size)
  "Describe a bias-free SiLU-gated feed-forward component."
  (component-positive intermediate-size "feed-forward width" t)
  (make-instance 'swiglu :width intermediate-size))
(defun make-transformer-block (&key attention feed-forward (norm-epsilon 1e-5)
                                   (residual :sequential))
  "Describe a pre-RMSNorm block; :PARALLEL shares one normalized input."
  (unless (and (typep attention 'rotary-attention) (typep feed-forward 'swiglu)
               (member residual '(:sequential :parallel)))
    (fail 'compatibility-error "Expected rotary attention, SwiGLU, and a supported residual topology"))
  (component-positive norm-epsilon "normalization epsilon")
  (make-instance 'transformer-block :attention attention :feed-forward feed-forward
                 :epsilon norm-epsilon :residual residual))

(defgeneric component-config (component)
  (:documentation "Return a fresh JSON description in the supported composition vocabulary.
New Lisp descriptor classes may lower to this vocabulary; arbitrary code is not serialized."))
(defmethod component-config ((component t))
  (fail 'compatibility-error "No portable component description for ~S" component))
(defmethod component-config ((component rotary-attention))
  (component-object "type" "rope" "heads" (component-heads component)
                    "kv_heads" (component-kv-heads component) "theta" (component-theta component)))
(defmethod component-config ((component swiglu))
  (component-object "type" "swiglu" "intermediate_size" (component-width component)))
(defmethod component-config ((component transformer-block))
  (component-object "attention" (component-config (block-attention component))
                    "feed_forward" (component-config (block-feed-forward component))
                    "rms_norm_eps" (block-epsilon component)
                    "residual" (string-downcase (symbol-name (block-residual component)))))
(defun block-from-config (config)
  (component-keys config '("attention" "feed_forward" "rms_norm_eps" "residual"))
  (let ((attention (gethash "attention" config)) (ffn (gethash "feed_forward" config)))
    (component-keys attention '("type" "heads" "kv_heads" "theta"))
    (component-keys ffn '("type" "intermediate_size"))
    (unless (and (equal (gethash "type" attention) "rope")
                 (equal (gethash "type" ffn) "swiglu")
                 (member (gethash "residual" config) '("sequential" "parallel") :test #'equal))
      (fail 'compatibility-error "Unregistered component semantics"))
    (make-transformer-block
     :attention (make-rotary-attention :heads (gethash "heads" attention)
                                      :kv-heads (gethash "kv_heads" attention)
                                      :rope-theta (gethash "theta" attention))
     :feed-forward (make-swiglu :intermediate-size (gethash "intermediate_size" ffn))
     :norm-epsilon (gethash "rms_norm_eps" config)
     :residual (if (equal (gethash "residual" config) "sequential") :sequential :parallel))))

(defparameter +composed-config-keys+
  '("architectures" "model_type" "composition_version" "block_configs"
    "vocab_size" "hidden_size" "num_hidden_layers" "max_position_embeddings"
    "rms_norm_eps" "tie_word_embeddings" "initializer_range" "use_cache"
    "bos_token_id" "eos_token_id" "pad_token_id" "dtype" "torch_dtype"
    "auto_map" "transformers_version" "_name_or_path" "_commit_hash"
    "return_dict" "output_attentions" "output_hidden_states"))
(defun composed-auto-map ()
  (component-object "AutoConfig" "configuration_tb_composed.TBComposedConfig"
                    "AutoModelForCausalLM" "modeling_tb_composed.TBComposedForCausalLM"))
(defmethod validate-architecture-config ((architecture (eql 'composed-causal-lm)) config)
  (declare (ignore architecture))
  (component-keys config +composed-config-keys+)
  (unless (and (equal (gethash "model_type" config) "tb_composed")
               (eql (gethash "composition_version" config) 1)
               (let ((names (gethash "architectures" config)))
                 (and (vectorp names) (= (length names) 1)
                      (equal (aref names 0) "TBComposedForCausalLM")))
               (eq (gethash "use_cache" config) 'yason:false)
               (member (gethash "tie_word_embeddings" config) '(yason:true yason:false)))
    (fail 'compatibility-error "Unsupported composed-model version or execution settings"))
  (dolist (key '("vocab_size" "hidden_size" "num_hidden_layers" "max_position_embeddings"))
    (component-positive (gethash key config) key t))
  (dolist (key '("initializer_range" "rms_norm_eps"))
    (component-positive (gethash key config) key))
  (dolist (key '("bos_token_id" "eos_token_id" "pad_token_id"))
    (unless (or (null (gethash key config))
                (eq (gethash key config) 'yason:null)
                (typep (gethash key config) `(integer 0 (,(gethash "vocab_size" config)))))
      (fail 'compatibility-error "Invalid composed token ID: ~A" key)))
  (let ((blocks (gethash "block_configs" config)))
    (unless (and (vectorp blocks) (not (stringp blocks))
                 (= (length blocks) (gethash "num_hidden_layers" config)))
      (fail 'compatibility-error "Block descriptions must match num_hidden_layers"))
    (loop for description across blocks for block = (block-from-config description)
          for heads = (component-heads (block-attention block)) do
      (unless (and (zerop (mod (gethash "hidden_size" config) heads))
                   (evenp (/ (gethash "hidden_size" config) heads)))
        (fail 'compatibility-error "Hidden size must give an even integral head dimension in every block"))))
  (let ((mapping (gethash "auto_map" config)))
    (when mapping
      (unless (same-component-data-p mapping (composed-auto-map))
        (fail 'compatibility-error "Composed auto_map does not match the emitted implementation"))))
  config)
(defun copy-component-data (value)
  (cond ((hash-table-p value)
         (let ((copy (make-hash-table :test 'equal)))
           (maphash (lambda (k v) (setf (gethash (copy-seq k) copy) (copy-component-data v))) value)
           copy))
        ((stringp value) (copy-seq value))
        ((vectorp value) (map 'vector #'copy-component-data value))
        ((consp value) (cons (copy-component-data (car value)) (copy-component-data (cdr value))))
        (t value)))
(defun same-component-data-p (a b)
  (cond ((hash-table-p a)
         (and (hash-table-p b) (= (hash-table-count a) (hash-table-count b))
              (loop for key being the hash-keys of a using (hash-value value)
                    always (multiple-value-bind (other present) (gethash key b)
                             (and present (same-component-data-p value other))))))
        ((stringp a) (and (stringp b) (string= a b)))
        ((vectorp a) (and (vectorp b) (not (stringp b)) (= (length a) (length b))
                         (every #'same-component-data-p a b)))
        ((consp a) (and (consp b) (same-component-data-p (car a) (car b))
                       (same-component-data-p (cdr a) (cdr b))))
        (t (eql a b))))
(defun validate-composition-state (model)
  (unless (same-component-data-p (model-config model) (construction-config model))
    (fail 'compatibility-error "Composed model configuration was mutated; construct a new model to change architecture")))
(defmethod initialize-instance :after ((model composed-causal-lm) &key)
  (setf (slot-value model 'blocks)
        (map 'vector #'block-from-config (gethash "block_configs" (model-config model)))
        (slot-value model 'construction-config) (copy-component-data (model-config model))))
(defgeneric transformer-blocks (model)
  (:documentation "Return fresh, non-owning component descriptions for a composed model."))
(defmethod transformer-blocks ((model composed-causal-lm))
  (map 'vector (lambda (block) (block-from-config (component-config block))) (composed-blocks model)))
(defmethod embedding-weight-name ((architecture (eql 'composed-causal-lm))) "model.embed_tokens.weight")
(defmethod default-tie-embeddings ((architecture (eql 'composed-causal-lm))) 'yason:false)

(defmethod architecture-parameter-schema ((architecture (eql 'composed-causal-lm)) config)
  (declare (ignore architecture))
  (let* ((hidden (gethash "hidden_size" config)) (vocab (gethash "vocab_size" config))
         (schema (list (cons "model.embed_tokens.weight" (list vocab hidden))
                       (cons "model.norm.weight" (list hidden)))))
    (unless (tied-embeddings-p config) (push (cons "lm_head.weight" (list vocab hidden)) schema))
    (loop for description across (gethash "block_configs" config) for index from 0
          for block = (block-from-config description)
          for attention = (block-attention block)
          for kv-width = (* (/ hidden (component-heads attention)) (component-kv-heads attention))
          for width = (component-width (block-feed-forward block)) do
      (dolist (entry `(("self_attn.q_proj.weight" ,hidden ,hidden)
                       ("self_attn.k_proj.weight" ,kv-width ,hidden)
                       ("self_attn.v_proj.weight" ,kv-width ,hidden)
                       ("self_attn.o_proj.weight" ,hidden ,hidden)
                       ("mlp.gate_proj.weight" ,width ,hidden)
                       ("mlp.up_proj.weight" ,width ,hidden)
                       ("mlp.down_proj.weight" ,hidden ,width)
                       ("input_layernorm.weight" ,hidden)))
        (push (cons (format nil "model.layers.~D.~A" index (car entry)) (cdr entry)) schema))
      (when (eq (block-residual block) :sequential)
        (push (cons (format nil "model.layers.~D.post_attention_layernorm.weight" index)
                    (list hidden)) schema))) schema))

;; Dispatch stays at component boundaries; tensor operations stay in native kernels.
(defgeneric component-forward (component model input prefix mask offset cache index))
(defmethod component-forward ((component swiglu) model input prefix mask offset cache index)
  (declare (ignore mask offset cache index))
  (let ((gate (project model input (concatenate 'string prefix "gate_proj.weight")))
        (up (project model input (concatenate 'string prefix "up_proj.weight"))))
    (project model (multiply (multiply gate (sigmoid gate)) up)
             (concatenate 'string prefix "down_proj.weight"))))
(defmethod component-forward ((component rotary-attention) model input prefix mask offset cache index)
  (let* ((batch (first (tensor-shape input))) (steps (second (tensor-shape input)))
         (dimension (/ (third (tensor-shape input)) (component-heads component))))
    (flet ((projection (name heads)
             (permute (reshape (project model input (concatenate 'string prefix name))
                               (list batch steps heads dimension)) '(0 2 1 3))))
      (let* ((q (rope (projection "q_proj.weight" (component-heads component)) dimension (component-theta component) offset))
             (k (rope (projection "k_proj.weight" (component-kv-heads component)) dimension (component-theta component) offset))
             (v (projection "v_proj.weight" (component-kv-heads component)))
             (entry (and cache (aref (cache-entries cache) index))) (next nil))
        (when cache
          (multiple-value-bind (used storage) (update-cache-tensor cache (first entry) k offset)
            (setf k used next (list storage)))
          (multiple-value-bind (used storage) (update-cache-tensor cache (second entry) v offset)
            (setf v used next (append next (list storage)))))
        (let* ((attended (attention q k v (/ 1.0 (sqrt (float dimension 1.0))) mask))
               (joined (reshape (permute attended '(0 2 1 3))
                                (list batch steps (* dimension (component-heads component))))))
          (values (project model joined (concatenate 'string prefix "o_proj.weight")) next))))))
(defmethod component-forward ((component transformer-block) model input prefix mask offset cache index)
  (let ((normalized (rms-norm input (weight model (concatenate 'string prefix "input_layernorm.weight"))
                              (block-epsilon component))))
    (multiple-value-bind (attended next)
        (component-forward (block-attention component) model normalized
                           (concatenate 'string prefix "self_attn.") mask offset cache index)
      (let* ((residual (add input attended))
             (ffn-input (if (eq (block-residual component) :parallel) normalized
                            (rms-norm residual (weight model (concatenate 'string prefix "post_attention_layernorm.weight"))
                                      (block-epsilon component)))))
        (values (add residual (component-forward (block-feed-forward component) model ffn-input
                                                 (concatenate 'string prefix "mlp.") mask offset cache index)) next)))))
(defmethod compute-logits ((model composed-causal-lm) ids mask offset &optional cache token-type-ids)
  (validate-composition-state model)
  (validate-token-type-ids model nil token-type-ids)
  (let* ((shape (tensor-shape ids)) (hidden (take-indices (weight model "model.embed_tokens.weight") ids))
         (mask (causal-mask (first shape) (second shape) offset mask))
         (entries (make-array (length (composed-blocks model)))))
    (loop for block across (composed-blocks model) for index from 0 do
      (multiple-value-bind (next entry)
          (component-forward block model hidden (format nil "model.layers.~D." index) mask offset cache index)
        (setf hidden next (aref entries index) entry)))
    (values (linear (rms-norm hidden (weight model "model.norm.weight") (config model "rms_norm_eps"))
                    (weight model (if (tied-embeddings-p (model-config model)) "model.embed_tokens.weight" "lm_head.weight")))
            entries)))

(defmethod model-export-config ((model composed-causal-lm))
  (validate-composition-state model)
  (let ((config (call-next-method))) (setf (gethash "auto_map" config) (composed-auto-map)) config))
(defmethod python-architecture-files ((model composed-causal-lm))
  (declare (ignore model))
  (loop for (folder . names) in '(("tb_parallel" "configuration_tb_parallel.py" "modeling_tb_parallel.py")
                                  ("tb_composed" "configuration_tb_composed.py" "modeling_tb_composed.py")) append
    (loop for name in names collect
      (cons name (asdf:system-relative-pathname "cl-transformer-blocks"
                                                (format nil "python/~A/~A" folder name))))))
(defmethod architecture-capabilities ((architecture (eql 'composed-causal-lm)) config directory)
  (declare (ignore architecture config directory))
  (list :operations '(:forward :training :training-checkpoint :export :cache :generation
                     :lora :rslora :custom-python-export)
        :mask-policy :right-padding
        :restrictions '("version-one rotary-attention/SwiGLU composition vocabulary"
                        "FP32, zero dropout, right padding, greedy generation"
                        "custom Python export requires trust_remote_code=True"
                        "Python generation recomputes prefixes; no Python KV cache")))

(defun make-transformer (&key vocab-size hidden-size blocks context-length
                             (norm-epsilon 1e-5) (tie-word-embeddings nil)
                             (initializer-range 0.02) (bos-token-id 1) (eos-token-id 2)
                             (pad-token-id 0) (seed 1) (device :cpu))
  "Build and initialize a decoder from an ordered sequence of component descriptions.
Components are snapshotted through the version-one export vocabulary; weights are not shared."
  (unless (and (typep blocks 'sequence) (not (stringp blocks)) (plusp (length blocks)))
    (fail 'compatibility-error "BLOCKS must be a nonempty list or vector of descriptions"))
  (let* ((config (component-object
                  "model_type" "tb_composed" "architectures" #("TBComposedForCausalLM")
                  "composition_version" 1 "block_configs" (map 'vector #'component-config blocks)
                  "num_hidden_layers" (length blocks) "hidden_size" hidden-size "vocab_size" vocab-size
                  "max_position_embeddings" context-length "rms_norm_eps" norm-epsilon
                  "initializer_range" initializer-range "use_cache" 'yason:false
                  "tie_word_embeddings" (if tie-word-embeddings 'yason:true 'yason:false)
                  "bos_token_id" bos-token-id "eos_token_id" eos-token-id "pad_token_id" pad-token-id
                  "dtype" "float32"))
         (arrays (portable-random-parameter-arrays (validate-config config) seed))
         (backend (make-backend :device device)) (parameters (make-hash-table :test 'equal)) (success nil))
    (unwind-protect
         (let ((model nil))
           (dolist (entry arrays)
             (setf (gethash (car entry) parameters) (tensor-from-array backend (cdr entry))))
           (setf model (make-instance 'composed-causal-lm :config config :backend backend :parameters parameters
                                      :directory nil :source-id "common-lisp:tb-composed" :source-revision nil)
                 success t) model)
      (unless success
        (maphash (lambda (name tensor) (declare (ignore name)) (dispose tensor)) parameters)
        (dispose backend)))))
