(in-package #:tb)
(defclass gpt2-model (model) ())
(register-architecture "gpt2" 'gpt2-model)

(defmethod architecture-capabilities ((architecture (eql 'gpt2-model)) config directory)
  (declare (ignore architecture directory))
  (let ((training (every (lambda (key) (zerop (gethash key config 0.0)))
                         '("resid_pdrop" "embd_pdrop" "attn_pdrop"))))
    (list :operations (append '(:forward :export :cache :generation)
                              (and training '(:training :training-checkpoint)))
          :mask-policy :right-padding
          :restrictions
          '("FP32 execution and export"
            "absolute learned positions"
            "greedy single-sequence generation"
            "training requires zero dropout"
            "native PEFT unavailable"))))
(defmethod embedding-weight-name ((architecture (eql 'gpt2-model))) "transformer.wte.weight")
(defmethod default-tie-embeddings ((architecture (eql 'gpt2-model))) 'yason:true)
(defmethod model-layer-count ((model gpt2-model)) (config model "n_layer"))
(defmethod model-context-length ((model gpt2-model)) (config model "n_positions"))
(defparameter +gpt2-config-keys+
  '("model_type" "architectures" "vocab_size" "n_embd" "n_layer" "n_head" "n_positions" "n_ctx" "n_inner"
    "activation_function" "resid_pdrop" "embd_pdrop" "attn_pdrop" "layer_norm_epsilon" "initializer_range"
    "summary_type" "summary_use_proj" "summary_activation" "summary_proj_to_labels" "summary_first_dropout"
    "scale_attn_weights" "scale_attn_by_inverse_layer_idx" "reorder_and_upcast_attn" "add_cross_attention"
    "use_cache" "bos_token_id" "eos_token_id" "pad_token_id" "tie_word_embeddings"
    "dtype" "torch_dtype" "transformers_version" "_name_or_path" "_commit_hash" "_attn_implementation_autoset"
    "return_dict" "output_hidden_states" "output_attentions" "task_specific_params"
    "_num_labels" "id2label" "label2id" "problem_type"))
(defmethod validate-architecture-config ((architecture (eql 'gpt2-model)) c)
  (maphash (lambda (key value) (declare (ignore value))
             (unless (member key +gpt2-config-keys+ :test #'equal)
               (fail 'compatibility-error "Unrecognized GPT-2 configuration field: ~A" key))) c)
  (dolist (key '("vocab_size" "n_embd" "n_layer" "n_head" "n_positions"))
    (unless (typep (gethash key c) '(integer 1 2147483647))
      (fail 'compatibility-error "Invalid GPT-2 dimension: ~A" key)))
  (unless (and (zerop (mod (gethash "n_embd" c) (gethash "n_head" c)))
               (or (null (gethash "n_inner" c)) (typep (gethash "n_inner" c) '(integer 1))))
    (fail 'compatibility-error "Invalid GPT-2 head or feed-forward dimensions"))
  (unless (member (gethash "activation_function" c "gelu_new") '("gelu_new" "gelu") :test #'equal)
    (fail 'compatibility-error "Only GPT-2 GELU and GELU-new are supported"))
  (dolist (key '("add_cross_attention" "reorder_and_upcast_attn"))
    (when (json-true-p (gethash key c)) (fail 'compatibility-error "Unsupported GPT-2 option: ~A" key)))
  (dolist (key '("resid_pdrop" "embd_pdrop" "attn_pdrop"))
    (let ((p (gethash key c 0.1)))
      (unless (and (realp p) (<= 0 p) (< p 1)) (fail 'compatibility-error "Invalid dropout: ~A" key))))
  (unless (and (realp (gethash "layer_norm_epsilon" c 1e-5)) (> (gethash "layer_norm_epsilon" c 1e-5) 0))
    (fail 'compatibility-error "Invalid GPT-2 layer norm epsilon")) c)
(defmethod validate-training-config ((model gpt2-model))
  (dolist (key '("resid_pdrop" "embd_pdrop" "attn_pdrop"))
    (unless (zerop (config model key 0.1))
      (fail 'compatibility-error "Native GPT-2 training requires zero configured dropout (~A)" key))))
(defmethod architecture-parameter-schema ((architecture (eql 'gpt2-model)) c)
  (let* ((d (gethash "n_embd" c)) (inner (or (gethash "n_inner" c) (* 4 d)))
         (schema `(("transformer.wte.weight" ,(gethash "vocab_size" c) ,d)
                   ("transformer.wpe.weight" ,(gethash "n_positions" c) ,d)
                   ("transformer.ln_f.weight" ,d) ("transformer.ln_f.bias" ,d))))
    (unless (tied-embeddings-p c) (push (list "lm_head.weight" (gethash "vocab_size" c) d) schema))
    (dotimes (i (gethash "n_layer" c))
      (dolist (entry `(("ln_1.weight" ,d) ("ln_1.bias" ,d) ("ln_2.weight" ,d) ("ln_2.bias" ,d)
                       ("attn.c_attn.weight" ,d ,(* 3 d)) ("attn.c_attn.bias" ,(* 3 d))
                       ("attn.c_proj.weight" ,d ,d) ("attn.c_proj.bias" ,d)
                       ("mlp.c_fc.weight" ,d ,inner) ("mlp.c_fc.bias" ,inner)
                       ("mlp.c_proj.weight" ,inner ,d) ("mlp.c_proj.bias" ,d)))
        (push (cons (format nil "transformer.h.~D.~A" i (car entry)) (cdr entry)) schema))) schema))
(defmethod project ((model gpt2-model) inputs parameter-name)
  "GPT-2 Conv1D stores (input,output) weights, unlike Llama Linear."
  (add (matmul inputs (weight model parameter-name))
       (weight model (concatenate 'string (subseq parameter-name 0 (- (length parameter-name) 6)) "bias"))))
(defclass gpt2-layer () ((index :initarg :index :reader layer-index)))
(defmethod apply-layer ((layer gpt2-layer) (model gpt2-model) hidden mask offset cache)
  (let* ((d (config model "n_embd")) (heads (config model "n_head")) (hd (/ d heads))
         (batch (first (tensor-shape hidden))) (steps (second (tensor-shape hidden)))
         (eps (config model "layer_norm_epsilon" 1e-5))
         (scale (if (json-true-p (config model "scale_attn_weights" 'yason:true)) (/ 1.0 (sqrt (float hd 1.0))) 1.0)))
    (when (json-true-p (config model "scale_attn_by_inverse_layer_idx")) (setf scale (/ scale (1+ (layer-index layer)))))
    (flet ((w (suffix) (weight model (format nil "transformer.h.~D.~A" (layer-index layer) suffix)))
           (p (input suffix) (project model input (format nil "transformer.h.~D.~A" (layer-index layer) suffix)))
           (heads (qkv start) (permute (reshape (slice-tensor qkv (list 0 0 start) (list batch steps (+ start d)))
                                                (list batch steps heads hd)) '(0 2 1 3))))
      (let* ((qkv (p (layer-norm hidden (w "ln_1.weight") (w "ln_1.bias") eps) "attn.c_attn.weight"))
             (q (heads qkv 0)) (k (heads qkv d)) (v (heads qkv (* 2 d)))
             (entry (and cache (aref (cache-entries cache) (layer-index layer))))
             (next-entry nil))
        (when cache
          (multiple-value-bind (used storage)
              (update-cache-tensor cache (and entry (first entry)) k offset)
            (setf k used next-entry (list storage)))
          (multiple-value-bind (used storage)
              (update-cache-tensor cache (and entry (second entry)) v offset)
            (setf v used next-entry (nconc next-entry (list storage)))))
        (let* ((attended (reshape (permute (attention q k v scale mask) '(0 2 1 3)) (list batch steps d)))
               (residual (add hidden (p attended "attn.c_proj.weight")))
               (normalized (layer-norm residual (w "ln_2.weight") (w "ln_2.bias") eps))
               (ffn (p (gelu (p normalized "mlp.c_fc.weight")
                             (equal (config model "activation_function" "gelu_new") "gelu_new")) "mlp.c_proj.weight")))
          (values (add residual ffn) next-entry))))))
(defmethod compute-logits ((model gpt2-model) ids padding offset &optional cache token-type-ids)
  (validate-token-type-ids model nil token-type-ids)
  (let* ((shape (tensor-shape ids)) (batch (first shape)) (steps (second shape))
         (positions (make-array steps)) (entries (make-array (model-layer-count model))))
    (dotimes (i steps) (setf (aref positions i) (+ offset i)))
    (let ((hidden (add (take-indices (weight model "transformer.wte.weight") ids)
                       (take-indices (weight model "transformer.wpe.weight") (tensor-from-array *backend* positions :dtype :int32))))
          (mask (causal-mask batch steps offset padding)))
      (dotimes (i (length entries))
        (multiple-value-bind (next entry)
            (apply-layer (make-instance 'gpt2-layer :index i) model hidden mask offset cache)
          (setf hidden next (aref entries i) entry)))
      (values (linear (layer-norm hidden (weight model "transformer.ln_f.weight") (weight model "transformer.ln_f.bias")
                                  (config model "layer_norm_epsilon" 1e-5))
                      (weight model (if (tied-embeddings-p (model-config model)) "transformer.wte.weight" "lm_head.weight"))) entries))))

(defmethod sanitize-architecture-weights ((architecture (eql 'gpt2-model)) config weights)
  ;; Older GPT-2 checkpoints serialize a fixed causal-mask buffer. Validate its
  ;; complete contents before dropping it; never treat arbitrary extras as buffers.
  (let ((n (gethash "n_positions" config)))
    (dotimes (layer (gethash "n_layer" config))
      (let* ((name (format nil "transformer.h.~D.attn.bias" layer)) (value (gethash name weights)))
        (when value
          (unless (equal (tensor-shape value) (list 1 1 n n))
            (fail 'compatibility-error "Invalid legacy causal mask shape: ~A" name))
          (let ((a (tensor-array value)))
            (declare (type (simple-array single-float (* * * *)) a))
            (dotimes (i n) (dotimes (j n)
              (unless (= (aref a 0 0 i j) (if (<= j i) 1.0 0.0))
                (fail 'compatibility-error "Modified legacy causal mask: ~A" name)))))
          (dispose value) (remhash name weights))))))
