(in-package #:tb)

(defclass kv-cache ()
  ((model :initarg :model :reader cache-model)
   (version :initarg :version :reader cache-version)
   (entries :initarg :entries :accessor cache-entries)
   (offset :initform 0 :accessor cache-offset :reader cache-length)
   (capacity :initform 0 :accessor %cache-capacity)
   (growth-step :initarg :growth-step :reader cache-growth-step)
   (batch :initform nil :accessor cache-batch)
   (disposed :initform nil :accessor cache-disposed)))
(defmethod make-cache ((model model) &key (growth-step 256))
  (pointer (model-backend model))
  (unless (typep growth-step '(integer 1))
    (fail 'shape-error "Cache growth step must be a positive integer"))
  (make-instance 'kv-cache :model model :version (model-version model)
                 :growth-step growth-step
                 :entries (make-array (model-layer-count model) :initial-element nil)))
(defun cache-capacity (cache)
  "Return the number of token positions currently reserved in CACHE."
  (%cache-capacity cache))
(defmethod dispose ((cache kv-cache))
  (loop for entry across (cache-entries cache) do (mapc #'dispose entry))
  (fill (cache-entries cache) nil) (setf (cache-disposed cache) t))
(defvar *parameter-overrides* nil)
(defun weight (model name)
  (or (and *parameter-overrides* (gethash name *parameter-overrides*))
      (gethash name (parameters model))
      (fail 'compatibility-error "Missing parameter ~A" name)))
(defun linear (a weight) (matmul a (permute weight '(1 0))))
(defgeneric project (model inputs parameter-name))
(defmethod project ((model model) inputs parameter-name)
  (linear inputs (weight model parameter-name)))
(defclass llama-layer () ((index :initarg :index :reader layer-index)))
(defun next-cache-capacity (cache required)
  (if (<= required (%cache-capacity cache))
      (%cache-capacity cache)
      (min (model-context-length (cache-model cache))
           (* (cache-growth-step cache)
              (ceiling required (cache-growth-step cache))))))
(defun extend-cache-tensor (tensor shape capacity)
  (let ((current (if tensor (third (tensor-shape tensor)) 0)))
    (cond ((= current capacity) tensor)
          ((zerop current)
           (zeros (list (first shape) (second shape) capacity (fourth shape))))
          (t
           (concatenate-tensors
            tensor
            (zeros (list (first shape) (second shape) (- capacity current) (fourth shape)))
            2)))))
(defun update-cache-tensor (cache tensor update offset)
  (let* ((shape (tensor-shape update))
         (end (+ offset (third shape)))
         (capacity (next-cache-capacity cache end))
         (storage (extend-cache-tensor tensor shape capacity))
         (updated (slice-update storage update
                                (list 0 0 offset 0)
                                (list (first shape) (second shape) end (fourth shape)))))
    (values (slice-tensor updated '(0 0 0 0)
                          (list (first shape) (second shape) end (fourth shape)))
            updated)))
(defgeneric apply-layer (layer model hidden mask offset cache))
(defmethod apply-layer ((layer llama-layer) (model llama-model) hidden mask offset cache)
  (let* ((c (model-config model))
         (heads (config model "num_attention_heads"))
         (kv-heads (config model "num_key_value_heads" heads)) (hd (head-dimension c))
         (eps (config model "rms_norm_eps")) (batch (first (tensor-shape hidden)))
         (steps (second (tensor-shape hidden))))
    (flet ((p (input suffix) (project model input (format nil "model.layers.~D.~A" (layer-index layer) suffix)))
           (w (suffix) (weight model (format nil "model.layers.~D.~A" (layer-index layer) suffix)))
           (split-heads (a count) (permute (reshape a (list batch steps count hd)) '(0 2 1 3))))
      (let* ((normalized (rms-norm hidden (w "input_layernorm.weight") eps))
             (q (rope (split-heads (p normalized "self_attn.q_proj.weight") heads) hd (rope-base c) offset))
             (k (rope (split-heads (p normalized "self_attn.k_proj.weight") kv-heads) hd (rope-base c) offset))
             (v (split-heads (p normalized "self_attn.v_proj.weight") kv-heads))
             (entry (and cache (aref (cache-entries cache) (layer-index layer))))
             (next-entry nil))
        (when cache
          (multiple-value-bind (used storage)
              (update-cache-tensor cache (and entry (first entry)) k offset)
            (setf k used next-entry (list storage)))
          (multiple-value-bind (used storage)
              (update-cache-tensor cache (and entry (second entry)) v offset)
            (setf v used next-entry (nconc next-entry (list storage)))))
        (let* ((attended (attention q k v (/ 1.0 (sqrt (float hd 1.0))) mask))
               (joined (reshape (permute attended '(0 2 1 3)) (list batch steps (* heads hd))))
               (residual (add hidden (p joined "self_attn.o_proj.weight")))
               (normalized (rms-norm residual (w "post_attention_layernorm.weight") eps))
               (gate (p normalized "mlp.gate_proj.weight"))
               (up (p normalized "mlp.up_proj.weight")))
          (values (add residual (p (multiply (multiply gate (sigmoid gate)) up) "mlp.down_proj.weight"))
                  next-entry))))))
(defun validate-inputs (model ids mask cache)
  (unless (and (arrayp ids) (= 2 (array-rank ids))
               (> (array-dimension ids 0) 0) (> (array-dimension ids 1) 0))
    (fail 'shape-error "Token IDs must be a nonempty (batch,time) Lisp array"))
  (dotimes (i (array-total-size ids))
    (unless (typep (row-major-aref ids i) `(integer 0 (,(config model "vocab_size"))))
      (fail 'shape-error "Token ID out of vocabulary: ~S" (row-major-aref ids i))))
  (let* ((b (array-dimension ids 0)) (n (array-dimension ids 1))
         (offset (if cache (cache-offset cache) 0)))
    (when cache
      (unless (and (not (cache-disposed cache)) (eq (cache-model cache) model)
                   (= (cache-version cache) (model-version model))
                   (or (null (cache-batch cache)) (= b (cache-batch cache))))
        (fail 'compatibility-error "Cache is disposed, stale, or belongs to another model/batch")))
    (when (> (+ n offset) (model-context-length model))
      (fail 'shape-error "Sequence exceeds configured context length"))
    (when mask
      (unless (and (arrayp mask) (equal (array-dimensions mask) (list b (+ n offset))))
        (fail 'shape-error "Attention mask must cover (batch,total-cache-and-input-time)"))
      (dotimes (i (array-total-size mask))
        (unless (member (row-major-aref mask i) '(0 1))
          (fail 'shape-error "Attention mask values must be 0 or 1")))
      ;; This first contract uses absolute positions and right padding. Reject left padding.
      (dotimes (batch b)
        (let ((padding nil))
          (dotimes (i (+ n offset))
            (if (zerop (aref mask batch i)) (setf padding t)
                (when padding (fail 'compatibility-error "Only right padding is supported"))))
          (when (zerop (aref mask batch 0)) (fail 'shape-error "A batch row cannot be fully masked")))))
    (values b n offset)))
(defun causal-mask (batch steps offset padding)
  (let ((mask (make-array (list batch 1 steps (+ steps offset)) :element-type 'single-float)))
    (dotimes (b batch) (dotimes (q steps) (dotimes (k (+ steps offset))
      (setf (aref mask b 0 q k)
            (if (and (<= k (+ q offset)) (or (null padding) (= 1 (aref padding b k))))
                0.0 most-negative-single-float)))))
    (tensor-from-array *backend* mask)))
(defgeneric validate-token-type-ids (model inputs token-type-ids))
(defmethod validate-token-type-ids ((model model) inputs token-type-ids)
  (declare (ignore inputs))
  (when token-type-ids
    (fail 'compatibility-error "Native token-type IDs are unavailable for ~A"
          (config model "model_type"))))
(defgeneric compute-logits (model ids mask offset &optional cache token-type-ids))
(defmethod compute-logits ((model llama-model) ids mask offset &optional cache token-type-ids)
  "Construct the native graph without evaluation; also used under MLX autodiff."
  (validate-token-type-ids model nil token-type-ids)
  (let* ((shape (tensor-shape ids)) (hidden (take-indices (weight model "model.embed_tokens.weight") ids))
         (mask (causal-mask (first shape) (second shape) offset mask))
         (entries (make-array (model-layer-count model))))
    (dotimes (i (length entries))
      (multiple-value-bind (next entry)
          (apply-layer (make-instance 'llama-layer :index i) model hidden mask offset cache)
        (setf hidden next (aref entries i) entry)))
    (values (linear (rms-norm hidden (weight model "model.norm.weight") (config model "rms_norm_eps"))
                    (weight model (if (json-true-p (config model "tie_word_embeddings"))
                                      "model.embed_tokens.weight" "lm_head.weight"))) entries)))
(defmethod forward ((model model) inputs &key cache attention-mask token-type-ids)
  (pointer (model-backend model))
  (multiple-value-bind (batch steps offset) (validate-inputs model inputs attention-mask cache)
    (validate-token-type-ids model inputs token-type-ids)
    (let ((*backend* (model-backend model)))
      (with-tensor-scope
        (multiple-value-bind (logits entries)
            (compute-logits model (tensor-from-array *backend* inputs :dtype :int32)
                            attention-mask offset cache
                            (when token-type-ids
                              (tensor-from-array *backend* token-type-ids :dtype :int32)))
          ;; Complete device work before committing cache state or releasing graph temporaries.
          (checked-status (%tb-tensor-eval (pointer logits)))
          (when cache
            (dotimes (i (length entries))
              (let ((new (mapcar #'retain-tensor (aref entries i))))
                (mapc #'dispose (aref (cache-entries cache) i))
                (setf (aref (cache-entries cache) i) new)))
            (setf (cache-offset cache) (+ offset steps)
                  (%cache-capacity cache) (next-cache-capacity cache (+ offset steps))
                  (cache-batch cache) batch))
          (retain-tensor logits))))))
