(in-package #:tb)

(defvar *native-loaded* nil)
(defvar *backend* nil)
(defun ensure-native ()
  (unless *native-loaded*
    (let* ((root (asdf:system-source-directory "cl-transformer-blocks"))
           (library (or (uiop:getenv "TB_MLX_LIBRARY")
                        (namestring (merge-pathnames
                          #+darwin ".build/native/libtb_mlx.dylib"
                          #-darwin ".build/native/libtb_mlx.so" root)))))
      (cffi:load-foreign-library library)
      (setf *native-loaded* t))))

;; Declare repeated pointer-only ABI operations at compile time.
(defmacro define-native (name result &rest args)
  (let* ((symbol (intern (concatenate 'string "%" (string-upcase (substitute #\- #\_ name))) :tb))
         (raw (intern (concatenate 'string (symbol-name symbol) "-RAW") :tb))
         (variables (mapcar #'first args)))
    `(progn
       (cffi:defcfun (,name ,raw) ,result ,@args)
       (defun ,symbol ,variables
         ;; Native ML libraries expect IEEE masked exceptions, unlike SBCL defaults.
         #+sbcl (sb-int:with-float-traps-masked (:invalid :divide-by-zero :overflow :underflow :inexact)
                  (,raw ,@variables))
         #-sbcl (,raw ,@variables)))))
(define-native "tb_last_error" :string)
(define-native "tb_directory_create" :int (path :string))
(define-native "tb_directory_publish" :int (staging :string) (destination :string))
(define-native "tb_context_new" :pointer (gpu :int))
(define-native "tb_context_free" :void (context :pointer))
(define-native "tb_synchronize" :int (context :pointer))
(define-native "tb_tensor_free" :void (tensor :pointer))
(define-native "tb_tensor_retain" :pointer (tensor :pointer))
(define-native "tb_tensor_rank" :int (tensor :pointer))
(define-native "tb_tensor_dim" :int (tensor :pointer) (axis :int))
(define-native "tb_tensor_dtype" :int (tensor :pointer))
(define-native "tb_tensor_eval" :int (tensor :pointer))
(define-native "tb_tensor_float" :pointer (data :pointer) (shape :pointer) (rank :int))
(define-native "tb_tensor_int" :pointer (data :pointer) (shape :pointer) (rank :int))
(define-native "tb_tensor_copy_float" :int (context :pointer) (tensor :pointer) (data :pointer) (size :size))
(define-native "tb_tensor_copy_int" :int (context :pointer) (tensor :pointer) (data :pointer) (size :size))
(defmacro define-binary-operation (name)
  (let ((foreign (concatenate 'string "tb_" (string-downcase name))))
    `(progn
       (define-native ,foreign :pointer (context :pointer) (a :pointer) (b :pointer))
       (defun ,name (a b)
         (wrap-tensor (,(intern (concatenate 'string "%" (string-upcase (substitute #\- #\_ foreign))) :tb)
                       (pointer *backend*) (pointer a) (pointer b)) *backend*)))))
(define-binary-operation matmul)
(define-binary-operation add)
(define-binary-operation multiply)
(define-binary-operation subtract)
(define-native "tb_sigmoid" :pointer (context :pointer) (a :pointer))
(define-native "tb_cast_float" :pointer (context :pointer) (a :pointer))
(define-native "tb_cast_float16" :pointer (context :pointer) (a :pointer))
(define-native "tb_reshape" :pointer (context :pointer) (a :pointer) (shape :pointer) (rank :int))
(define-native "tb_permute" :pointer (context :pointer) (a :pointer) (axes :pointer) (rank :int))
(define-native "tb_take" :pointer (context :pointer) (a :pointer) (ids :pointer) (axis :int))
(define-native "tb_slice" :pointer (context :pointer) (a :pointer) (start :pointer) (stop :pointer) (rank :int))
(define-native "tb_zeros" :pointer (context :pointer) (shape :pointer) (rank :int))
(define-native "tb_slice_update" :pointer (context :pointer) (source :pointer) (update :pointer)
               (start :pointer) (stop :pointer) (rank :int))
(define-native "tb_concat" :pointer (context :pointer) (a :pointer) (b :pointer) (axis :int))
(define-native "tb_rms_norm" :pointer (context :pointer) (a :pointer) (weight :pointer) (eps :float))
(define-native "tb_rope" :pointer (context :pointer) (a :pointer) (dims :int) (base :float) (offset :int))
(define-native "tb_attention" :pointer (context :pointer) (q :pointer) (k :pointer) (v :pointer)
               (scale :float) (mask :pointer))
(define-native "tb_cross_entropy" :pointer (context :pointer) (logits :pointer) (labels :pointer))

(defclass native-resource () ((handle :initarg :handle :accessor handle)))
(defclass backend (native-resource) ((device :initarg :device :reader backend-device)))
(defclass tensor (native-resource) ((backend :initarg :backend :reader tensor-backend)))
(defvar *backend* nil)
(defvar *tensor-scope* nil)
(defvar *scoped-p* nil)
(defun pointer (object)
  (let ((p (handle object)))
    (when (cffi:null-pointer-p p) (fail 'backend-error "Resource has been disposed")) p))
(defun checked-pointer (p)
  (when (cffi:null-pointer-p p) (fail 'backend-error "MLX: ~A" (%tb-last-error))) p)
(defun checked-status (status)
  (unless (zerop status) (fail 'backend-error "MLX: ~A" (%tb-last-error))))
(defun checked-filesystem-status (status)
  (unless (zerop status) (fail 'compatibility-error "Filesystem: ~A" (%tb-last-error))))
(defun native-directory-path (path)
  (string-right-trim '(#\/ #\\) (uiop:native-namestring path)))
(defun publish-directory (staging destination)
  (ensure-native)
  (checked-filesystem-status
   (%tb-directory-publish (native-directory-path staging)
                          (native-directory-path destination))))
(defun create-directory-exclusively (path)
  (ensure-native)
  (%tb-directory-create (native-directory-path path)))
(defun make-backend (&key (device :cpu))
  "Create an explicit MLX :CPU or :GPU device. Unavailable devices signal an error."
  (ensure-native)
  (unless (member device '(:cpu :gpu)) (fail 'backend-error "Unknown device ~S" device))
  (let* ((p (checked-pointer (%tb-context-new (if (eq device :gpu) 1 0))))
         (object (make-instance 'backend :handle p :device device)))
    (trivial-garbage:finalize object (lambda () (%tb-context-free p))) object))
(defmethod dispose ((object backend))
  (unless (cffi:null-pointer-p (handle object))
    (trivial-garbage:cancel-finalization object)
    (%tb-context-free (handle object)) (setf (handle object) (cffi:null-pointer))))
(defmethod dispose ((object tensor))
  (unless (cffi:null-pointer-p (handle object))
    (trivial-garbage:cancel-finalization object)
    (%tb-tensor-free (handle object)) (setf (handle object) (cffi:null-pointer))))
(defun wrap-tensor (p backend)
  (let ((object (make-instance 'tensor :handle (checked-pointer p) :backend backend)))
    (if *scoped-p* (push object *tensor-scope*)
        (trivial-garbage:finalize object (lambda () (%tb-tensor-free p)))) object))
(defmacro with-tensor-scope (&body body)
  `(let ((*scoped-p* t) (*tensor-scope* nil))
     (unwind-protect (progn ,@body) (mapc #'dispose *tensor-scope*))))
(defun retain-tensor (tensor)
  (let ((*scoped-p* nil))
    (wrap-tensor (%tb-tensor-retain (pointer tensor)) (tensor-backend tensor))))
(defmacro with-int-vector ((pointer values) &body body)
  (let ((data (gensym "VALUES")))
    `(let ((,data ,values))
       (cffi:with-foreign-object (,pointer :int (length ,data))
         (loop for value in ,data for index from 0
               do (setf (cffi:mem-aref ,pointer :int index) value)) ,@body))))
(defun tensor-from-array (backend data &key (dtype :float32))
  "Copy a Lisp array into an owned native tensor. Scalars use rank-zero arrays."
  (pointer backend)
  (unless (and (arrayp data) (every (lambda (x) (< 0 x (expt 2 31))) (array-dimensions data)))
    (fail 'shape-error "Expected a nonempty array"))
  (unless (member dtype '(:float32 :int32)) (fail 'backend-error "Unsupported dtype ~S" dtype))
  (let ((type (if (eq dtype :int32) :int :float)))
    (cffi:with-foreign-object (buffer type (array-total-size data))
      (dotimes (i (array-total-size data))
        (let ((value (row-major-aref data i)))
          (when (and (eq dtype :int32) (not (typep value '(signed-byte 32))))
            (fail 'shape-error "Index ~S is not int32" value))
          (setf (cffi:mem-aref buffer type i) (if (eq type :float) (float value 1.0) value))))
      (with-int-vector (shape (array-dimensions data))
        (wrap-tensor (funcall (if (eq dtype :int32) #'%tb-tensor-int #'%tb-tensor-float)
                              buffer shape (array-rank data)) backend)))))
(defmethod tensor-shape ((a tensor))
  (loop for i below (%tb-tensor-rank (pointer a)) collect (%tb-tensor-dim (pointer a) i)))
(defmethod tensor-dtype ((a tensor))
  (aref #(:bool :uint8 :uint16 :uint32 :uint64 :int8 :int16 :int32 :int64
          :float16 :float32 :float64 :bfloat16 :complex64)
        (%tb-tensor-dtype (pointer a))))
(defmethod tensor-array ((a tensor))
  (let* ((shape (tensor-shape a)) (out (make-array shape :element-type 'single-float))
         (size (array-total-size out)))
    (cffi:with-foreign-object (buffer :float size)
      (checked-status (%tb-tensor-copy-float (pointer (tensor-backend a)) (pointer a) buffer size))
      (dotimes (i size) (setf (row-major-aref out i) (cffi:mem-aref buffer :float i)))) out))
(defun tensor-int-array (tensor)
  (unless (eq (tensor-dtype tensor) :int32)
    (fail 'backend-error "Integer tensor copy requires int32 dtype"))
  (let* ((shape (tensor-shape tensor))
         (out (make-array shape :element-type '(signed-byte 32)))
         (size (array-total-size out)))
    (cffi:with-foreign-object (buffer :int32 size)
      (checked-status
       (%tb-tensor-copy-int (pointer (tensor-backend tensor)) (pointer tensor) buffer size))
      (dotimes (index size)
        (setf (row-major-aref out index) (cffi:mem-aref buffer :int32 index))))
    out))
(defun reshape (a shape)
  (with-int-vector (p shape)
    (wrap-tensor (%tb-reshape (pointer *backend*) (pointer a) p (length shape)) *backend*)))
(defun permute (a axes)
  (with-int-vector (p axes)
    (wrap-tensor (%tb-permute (pointer *backend*) (pointer a) p (length axes)) *backend*)))
(defun take-indices (a ids &optional (axis 0))
  (wrap-tensor (%tb-take (pointer *backend*) (pointer a) (pointer ids) axis) *backend*))
(defun slice-tensor (a start stop)
  (with-int-vector (s start) (with-int-vector (e stop)
    (wrap-tensor (%tb-slice (pointer *backend*) (pointer a) s e (length start)) *backend*))))
(defun zeros (shape)
  (with-int-vector (p shape)
    (wrap-tensor (%tb-zeros (pointer *backend*) p (length shape)) *backend*)))
(defun slice-update (source update start stop)
  (with-int-vector (s start) (with-int-vector (e stop)
    (wrap-tensor (%tb-slice-update (pointer *backend*) (pointer source) (pointer update)
                                   s e (length start)) *backend*))))
(defun concatenate-tensors (a b axis)
  (wrap-tensor (%tb-concat (pointer *backend*) (pointer a) (pointer b) axis) *backend*))
(defun sigmoid (a)
  (wrap-tensor (%tb-sigmoid (pointer *backend*) (pointer a)) *backend*))
(defun cast-float (a)
  (wrap-tensor (%tb-cast-float (pointer *backend*) (pointer a)) *backend*))
(defun cast-float16 (a)
  (wrap-tensor (%tb-cast-float16 (pointer *backend*) (pointer a)) *backend*))
(defun rms-norm (a weight eps)
  (wrap-tensor (%tb-rms-norm (pointer *backend*) (pointer a) (pointer weight) (float eps 1.0)) *backend*))
(defun rope (a dims base offset)
  (wrap-tensor (%tb-rope (pointer *backend*) (pointer a) dims (float base 1.0) offset) *backend*))
(defun attention (q k v scale mask)
  (wrap-tensor (%tb-attention (pointer *backend*) (pointer q) (pointer k) (pointer v)
                              (float scale 1.0) (if mask (pointer mask) (cffi:null-pointer))) *backend*))
(defun cross-entropy (logits labels)
  (wrap-tensor (%tb-cross-entropy (pointer *backend*) (pointer logits) (pointer labels)) *backend*))

(define-binary-operation divide)
(define-native "tb_sqrt" :pointer (context :pointer) (a :pointer))
(define-native "tb_sum" :pointer (context :pointer) (a :pointer))
(define-native "tb_live_tensors" :size)
(define-native "tb_memory_stats" :int (context :pointer) (active :pointer) (cache :pointer) (peak :pointer))
(define-native "tb_reset_peak_memory" :int (context :pointer))
(define-native "tb_tensor_finite" :int (context :pointer) (a :pointer) (finite :pointer))
(defun scalar (value) (tensor-from-array *backend* (make-array nil :initial-element value)))
(defun tensor-sqrt (a) (wrap-tensor (%tb-sqrt (pointer *backend*) (pointer a)) *backend*))
(defun tensor-sum (a) (wrap-tensor (%tb-sum (pointer *backend*) (pointer a)) *backend*))
(defun require-finite (a)
  (cffi:with-foreign-object (finite :int)
    (checked-status (%tb-tensor-finite (pointer (tensor-backend a)) (pointer a) finite))
    (when (zerop (cffi:mem-ref finite :int)) (fail 'backend-error "Non-finite tensor; update aborted"))) a)
(defun backend-memory (backend)
  (cffi:with-foreign-objects ((active :size) (cache :size) (peak :size))
    (checked-status (%tb-memory-stats (pointer backend) active cache peak))
    (list :active (cffi:mem-ref active :size) :cache (cffi:mem-ref cache :size)
          :peak (cffi:mem-ref peak :size) :handles (%tb-live-tensors))))
(defun reset-backend-peak-memory (backend)
  "Synchronize BACKEND and reset MLX's process-wide peak allocation counter."
  (checked-status (%tb-reset-peak-memory (pointer backend)))
  backend)

(define-native "tb_tanh" :pointer (context :pointer) (a :pointer))
(define-native "tb_erf" :pointer (context :pointer) (a :pointer))
(define-native "tb_layer_norm" :pointer (context :pointer) (a :pointer) (weight :pointer) (bias :pointer) (eps :float))
(defun tensor-tanh (a) (wrap-tensor (%tb-tanh (pointer *backend*) (pointer a)) *backend*))
(defun tensor-erf (a) (wrap-tensor (%tb-erf (pointer *backend*) (pointer a)) *backend*))
(defun layer-norm (a weight bias eps)
  (wrap-tensor (%tb-layer-norm (pointer *backend*) (pointer a) (pointer weight) (pointer bias) (float eps 1.0)) *backend*))
(defun gelu (a approximate)
  (multiply (multiply (scalar 0.5) a)
            (add (scalar 1.0)
                 (if approximate
                     (tensor-tanh (multiply (scalar (sqrt (/ 2.0 pi)))
                                            (add a (multiply (scalar 0.044715) (multiply a (multiply a a))))))
                     (tensor-erf (multiply (scalar (/ 1.0 (sqrt 2.0))) a))))))
